[hls]
relative_roots=T:/SoC/Project/RTOS/ecg_hls_vitis_clean_project_v6/ecg_fpga_top
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=ecg_fpga_top/VITIS_LOOP_137_1 
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=ecg_fpga_top/beat_local dim=1 type=cyclic factor=2 variable=beat_local
syn.directive.loop_flatten=ecg_fpga_top/VITIS_LOOP_52_1  
syn.directive.array_partition=ecg_fpga_top/main5_dense_kernel dim=1 type=cyclic factor=41 variable=main5_dense_kernel
syn.directive.array_partition=ecg_fpga_top/main5_class_output_kernel dim=1 type=cyclic factor=12 variable=main5_class_output_kernel


