-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    prev : IN STD_LOGIC_VECTOR (15 downto 0);
    shl_ln : IN STD_LOGIC_VECTOR (8 downto 0);
    beat_in_q12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    beat_in_q12_ce0 : OUT STD_LOGIC;
    beat_in_q12_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    sum_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    sum_out_ap_vld : OUT STD_LOGIC;
    diff_sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    diff_sum_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_7FFF : STD_LOGIC_VECTOR (14 downto 0) := "111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln29_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln29_reg_318 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln29_reg_318_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_327 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_327_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_327_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_reg_332 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln36_fu_208_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln36_reg_338 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_343 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln37_fu_220_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln37_reg_348 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln32_fu_158_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal prev_1_fu_58 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal diff_sum_fu_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal diff_sum_1_fu_268_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal sum_fu_66 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal sum_1_fu_181_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal j_fu_70 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln29_fu_142_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal beat_in_q12_ce0_local : STD_LOGIC;
    signal zext_ln29_fu_148_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln31_fu_152_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln33_1_fu_177_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln33_1_fu_177_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln36_fu_198_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln33_fu_195_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln36_fu_198_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal d_fu_202_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal d_1_fu_233_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln36_1_fu_238_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_2_fu_250_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln36_fu_258_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_sum_2_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_fpga_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ecg_fpga_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    diff_sum_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    diff_sum_fu_62 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    diff_sum_fu_62 <= diff_sum_1_fu_268_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln29_fu_136_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_70 <= add_ln29_fu_142_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_70 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    prev_1_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    prev_1_fu_58 <= prev;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    prev_1_fu_58 <= x_reg_332;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    sum_fu_66 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    sum_fu_66 <= sum_1_fu_181_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln29_reg_318 <= icmp_ln29_fu_136_p2;
                icmp_ln29_reg_318_pp0_iter1_reg <= icmp_ln29_reg_318;
                icmp_ln35_reg_327 <= icmp_ln35_fu_163_p2;
                icmp_ln35_reg_327_pp0_iter1_reg <= icmp_ln35_reg_327;
                x_reg_332 <= beat_in_q12_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln35_reg_327_pp0_iter2_reg <= icmp_ln35_reg_327_pp0_iter1_reg;
                sub_ln37_reg_348 <= sub_ln37_fu_220_p2;
                tmp_reg_343 <= d_fu_202_p2(16 downto 16);
                trunc_ln36_reg_338 <= trunc_ln36_fu_208_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln29_fu_142_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv5_1));
    add_ln31_fu_152_p2 <= std_logic_vector(unsigned(zext_ln29_fu_148_p1) + unsigned(shl_ln));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln29_fu_136_p2)
    begin
        if (((icmp_ln29_fu_136_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_70;
        end if; 
    end process;

    beat_in_q12_address0 <= zext_ln32_fu_158_p1(9 - 1 downto 0);
    beat_in_q12_ce0 <= beat_in_q12_ce0_local;

    beat_in_q12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            beat_in_q12_ce0_local <= ap_const_logic_1;
        else 
            beat_in_q12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    d_1_fu_233_p3 <= 
        sub_ln37_reg_348 when (tmp_reg_343(0) = '1') else 
        trunc_ln36_reg_338;
    d_2_fu_250_p3 <= 
        ap_const_lv15_7FFF when (tmp_1_fu_242_p3(0) = '1') else 
        trunc_ln36_1_fu_238_p1;
    d_fu_202_p2 <= std_logic_vector(signed(sext_ln33_fu_195_p1) - signed(sext_ln36_fu_198_p1));
    diff_sum_1_fu_268_p3 <= 
        diff_sum_2_fu_262_p2 when (icmp_ln35_reg_327_pp0_iter2_reg(0) = '1') else 
        diff_sum_fu_62;
    diff_sum_2_fu_262_p2 <= std_logic_vector(unsigned(zext_ln36_fu_258_p1) + unsigned(diff_sum_fu_62));
    diff_sum_out <= diff_sum_fu_62;

    diff_sum_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln29_reg_318_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((icmp_ln29_reg_318_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            diff_sum_out_ap_vld <= ap_const_logic_1;
        else 
            diff_sum_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln29_fu_136_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv5_10) else "0";
    icmp_ln35_fu_163_p2 <= "0" when (ap_sig_allocacmp_j_1 = ap_const_lv5_0) else "1";
    sext_ln33_1_fu_177_p0 <= beat_in_q12_q0;
        sext_ln33_1_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln33_1_fu_177_p0),20));

        sext_ln33_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_reg_332),17));

    sext_ln36_fu_198_p0 <= prev_1_fu_58;
        sext_ln36_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_fu_198_p0),17));

    sub_ln37_fu_220_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln36_fu_208_p1));
    sum_1_fu_181_p2 <= std_logic_vector(signed(sext_ln33_1_fu_177_p1) + signed(sum_fu_66));
    sum_out <= sum_fu_66;

    sum_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln29_reg_318_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((icmp_ln29_reg_318_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            sum_out_ap_vld <= ap_const_logic_1;
        else 
            sum_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_242_p3 <= d_1_fu_233_p3(15 downto 15);
    trunc_ln36_1_fu_238_p1 <= d_1_fu_233_p3(15 - 1 downto 0);
    trunc_ln36_fu_208_p1 <= d_fu_202_p2(16 - 1 downto 0);
    zext_ln29_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_1),9));
    zext_ln32_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln31_fu_152_p2),64));
    zext_ln36_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(d_2_fu_250_p3),32));
end behav;
