-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln82 : IN STD_LOGIC_VECTOR (25 downto 0);
    zext_ln81_1 : IN STD_LOGIC_VECTOR (2 downto 0);
    in_q12_0_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_1_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_2_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_3_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_4_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_5_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_6_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_7_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_8_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_9_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_10_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_11_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_12_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_13_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_14_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_15_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_16_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_17_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_18_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_19_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_20_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_21_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_22_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_23_val : IN STD_LOGIC_VECTOR (14 downto 0);
    acc_2_out : OUT STD_LOGIC_VECTOR (32 downto 0);
    acc_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln84_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal main5_class_output_kernel_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal main5_class_output_kernel_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln81_1_cast_fu_326_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln81_1_cast_reg_536 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_4_reg_541 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln84_reg_547 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_547_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_547_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_547_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_cast_fu_359_p51 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_cast_reg_551 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_cast_reg_551_pp0_iter1_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln87_fu_489_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal acc_fu_142 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    signal grp_fu_512_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln82_cast_fu_330_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_sig_allocacmp_acc_load_2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal i_fu_146 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln84_fu_353_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal main5_class_output_kernel_ce0_local : STD_LOGIC;
    signal tmp_cast_fu_359_p49 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl_fu_471_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln86_fu_468_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln86_1_fu_478_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln86_fu_484_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_512_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_512_p00 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_cast_fu_359_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_359_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_fpga_top_sparsemux_49_5_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        din3 : IN STD_LOGIC_VECTOR (14 downto 0);
        din4 : IN STD_LOGIC_VECTOR (14 downto 0);
        din5 : IN STD_LOGIC_VECTOR (14 downto 0);
        din6 : IN STD_LOGIC_VECTOR (14 downto 0);
        din7 : IN STD_LOGIC_VECTOR (14 downto 0);
        din8 : IN STD_LOGIC_VECTOR (14 downto 0);
        din9 : IN STD_LOGIC_VECTOR (14 downto 0);
        din10 : IN STD_LOGIC_VECTOR (14 downto 0);
        din11 : IN STD_LOGIC_VECTOR (14 downto 0);
        din12 : IN STD_LOGIC_VECTOR (14 downto 0);
        din13 : IN STD_LOGIC_VECTOR (14 downto 0);
        din14 : IN STD_LOGIC_VECTOR (14 downto 0);
        din15 : IN STD_LOGIC_VECTOR (14 downto 0);
        din16 : IN STD_LOGIC_VECTOR (14 downto 0);
        din17 : IN STD_LOGIC_VECTOR (14 downto 0);
        din18 : IN STD_LOGIC_VECTOR (14 downto 0);
        din19 : IN STD_LOGIC_VECTOR (14 downto 0);
        din20 : IN STD_LOGIC_VECTOR (14 downto 0);
        din21 : IN STD_LOGIC_VECTOR (14 downto 0);
        din22 : IN STD_LOGIC_VECTOR (14 downto 0);
        din23 : IN STD_LOGIC_VECTOR (14 downto 0);
        def : IN STD_LOGIC_VECTOR (14 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component ecg_fpga_top_mac_muladd_15ns_14s_33s_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (32 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_main5_class_output_kernel_ROM_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component ecg_fpga_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    main5_class_output_kernel_U : component ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_main5_class_output_kernel_ROM_bkb
    generic map (
        DataWidth => 14,
        AddressRange => 120,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => main5_class_output_kernel_address0,
        ce0 => main5_class_output_kernel_ce0_local,
        q0 => main5_class_output_kernel_q0);

    sparsemux_49_5_15_1_1_U163 : component ecg_fpga_top_sparsemux_49_5_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 15,
        CASE1 => "00001",
        din1_WIDTH => 15,
        CASE2 => "00010",
        din2_WIDTH => 15,
        CASE3 => "00011",
        din3_WIDTH => 15,
        CASE4 => "00100",
        din4_WIDTH => 15,
        CASE5 => "00101",
        din5_WIDTH => 15,
        CASE6 => "00110",
        din6_WIDTH => 15,
        CASE7 => "00111",
        din7_WIDTH => 15,
        CASE8 => "01000",
        din8_WIDTH => 15,
        CASE9 => "01001",
        din9_WIDTH => 15,
        CASE10 => "01010",
        din10_WIDTH => 15,
        CASE11 => "01011",
        din11_WIDTH => 15,
        CASE12 => "01100",
        din12_WIDTH => 15,
        CASE13 => "01101",
        din13_WIDTH => 15,
        CASE14 => "01110",
        din14_WIDTH => 15,
        CASE15 => "01111",
        din15_WIDTH => 15,
        CASE16 => "10000",
        din16_WIDTH => 15,
        CASE17 => "10001",
        din17_WIDTH => 15,
        CASE18 => "10010",
        din18_WIDTH => 15,
        CASE19 => "10011",
        din19_WIDTH => 15,
        CASE20 => "10100",
        din20_WIDTH => 15,
        CASE21 => "10101",
        din21_WIDTH => 15,
        CASE22 => "10110",
        din22_WIDTH => 15,
        CASE23 => "10111",
        din23_WIDTH => 15,
        def_WIDTH => 15,
        sel_WIDTH => 5,
        dout_WIDTH => 15)
    port map (
        din0 => in_q12_0_val,
        din1 => in_q12_1_val,
        din2 => in_q12_2_val,
        din3 => in_q12_3_val,
        din4 => in_q12_4_val,
        din5 => in_q12_5_val,
        din6 => in_q12_6_val,
        din7 => in_q12_7_val,
        din8 => in_q12_8_val,
        din9 => in_q12_9_val,
        din10 => in_q12_10_val,
        din11 => in_q12_11_val,
        din12 => in_q12_12_val,
        din13 => in_q12_13_val,
        din14 => in_q12_14_val,
        din15 => in_q12_15_val,
        din16 => in_q12_16_val,
        din17 => in_q12_17_val,
        din18 => in_q12_18_val,
        din19 => in_q12_19_val,
        din20 => in_q12_20_val,
        din21 => in_q12_21_val,
        din22 => in_q12_22_val,
        din23 => in_q12_23_val,
        def => tmp_cast_fu_359_p49,
        sel => ap_sig_allocacmp_i_4,
        dout => tmp_cast_fu_359_p51);

    mac_muladd_15ns_14s_33s_33_4_1_U164 : component ecg_fpga_top_mac_muladd_15ns_14s_33s_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 15,
        din1_WIDTH => 14,
        din2_WIDTH => 33,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_512_p0,
        din1 => main5_class_output_kernel_q0,
        din2 => ap_sig_allocacmp_acc_load_2,
        ce => ap_const_logic_1,
        dout => grp_fu_512_p3);

    flow_control_loop_pipe_sequential_init_U : component ecg_fpga_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    acc_fu_142 <= sext_ln82_cast_fu_330_p1;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    acc_fu_142 <= grp_fu_512_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln84_fu_347_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_146 <= add_ln84_fu_353_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_146 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_4_reg_541 <= ap_sig_allocacmp_i_4;
                icmp_ln84_reg_547 <= icmp_ln84_fu_347_p2;
                icmp_ln84_reg_547_pp0_iter1_reg <= icmp_ln84_reg_547;
                tmp_cast_reg_551 <= tmp_cast_fu_359_p51;
                tmp_cast_reg_551_pp0_iter1_reg <= tmp_cast_reg_551;
                    zext_ln81_1_cast_reg_536(2 downto 0) <= zext_ln81_1_cast_fu_326_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln84_reg_547_pp0_iter2_reg <= icmp_ln84_reg_547_pp0_iter1_reg;
                icmp_ln84_reg_547_pp0_iter3_reg <= icmp_ln84_reg_547_pp0_iter2_reg;
            end if;
        end if;
    end process;
    zext_ln81_1_cast_reg_536(6 downto 3) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_2_out <= acc_fu_142;

    acc_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln84_reg_547_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln84_reg_547_pp0_iter3_reg = ap_const_lv1_1))) then 
            acc_2_out_ap_vld <= ap_const_logic_1;
        else 
            acc_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln84_fu_353_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv5_1));
    add_ln86_1_fu_478_p2 <= std_logic_vector(unsigned(p_shl_fu_471_p3) + unsigned(zext_ln86_fu_468_p1));
    add_ln86_fu_484_p2 <= std_logic_vector(unsigned(add_ln86_1_fu_478_p2) + unsigned(zext_ln81_1_cast_reg_536));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln84_fu_347_p2)
    begin
        if (((icmp_ln84_fu_347_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_2_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0, acc_fu_142, grp_fu_512_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_sig_allocacmp_acc_load_2 <= grp_fu_512_p3;
        else 
            ap_sig_allocacmp_acc_load_2 <= acc_fu_142;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_146)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_146;
        end if; 
    end process;

    grp_fu_512_p0 <= grp_fu_512_p00(15 - 1 downto 0);
    grp_fu_512_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_cast_reg_551_pp0_iter1_reg),29));
    icmp_ln84_fu_347_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv5_18) else "0";
    main5_class_output_kernel_address0 <= zext_ln87_fu_489_p1(7 - 1 downto 0);

    main5_class_output_kernel_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            main5_class_output_kernel_ce0_local <= ap_const_logic_1;
        else 
            main5_class_output_kernel_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_fu_471_p3 <= (i_4_reg_541 & ap_const_lv2_0);
        sext_ln82_cast_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln82),33));

    tmp_cast_fu_359_p49 <= "XXXXXXXXXXXXXXX";
    zext_ln81_1_cast_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln81_1),7));
    zext_ln86_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_4_reg_541),7));
    zext_ln87_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln86_fu_484_p2),64));
end behav;
