-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln58 : IN STD_LOGIC_VECTOR (4 downto 0);
    in_q12_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_18_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_19_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_21_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_22_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_23_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_24_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_25_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_26_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_27_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_28_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_29_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_30_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_31_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_32_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_33_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_34_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_35_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_36_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_37_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_38_val : IN STD_LOGIC_VECTOR (15 downto 0);
    in_q12_39_val : IN STD_LOGIC_VECTOR (15 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (32 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln61_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal main5_dense_kernel_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal main5_dense_kernel_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln58_cast_fu_482_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_cast_reg_764 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_3_reg_769 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln61_reg_775 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_775_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_775_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_775_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_511_p83 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_779 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_779_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln64_fu_717_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal acc_fu_208 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    signal grp_fu_740_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_sig_allocacmp_acc_load : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal i_fu_212 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln61_fu_505_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal main5_dense_kernel_ce0_local : STD_LOGIC;
    signal tmp_fu_511_p81 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln63_fu_684_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_fu_695_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_687_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln63_fu_702_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln63_fu_706_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln63_fu_712_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_511_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_511_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_fpga_top_sparsemux_81_6_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (15 downto 0);
        din14 : IN STD_LOGIC_VECTOR (15 downto 0);
        din15 : IN STD_LOGIC_VECTOR (15 downto 0);
        din16 : IN STD_LOGIC_VECTOR (15 downto 0);
        din17 : IN STD_LOGIC_VECTOR (15 downto 0);
        din18 : IN STD_LOGIC_VECTOR (15 downto 0);
        din19 : IN STD_LOGIC_VECTOR (15 downto 0);
        din20 : IN STD_LOGIC_VECTOR (15 downto 0);
        din21 : IN STD_LOGIC_VECTOR (15 downto 0);
        din22 : IN STD_LOGIC_VECTOR (15 downto 0);
        din23 : IN STD_LOGIC_VECTOR (15 downto 0);
        din24 : IN STD_LOGIC_VECTOR (15 downto 0);
        din25 : IN STD_LOGIC_VECTOR (15 downto 0);
        din26 : IN STD_LOGIC_VECTOR (15 downto 0);
        din27 : IN STD_LOGIC_VECTOR (15 downto 0);
        din28 : IN STD_LOGIC_VECTOR (15 downto 0);
        din29 : IN STD_LOGIC_VECTOR (15 downto 0);
        din30 : IN STD_LOGIC_VECTOR (15 downto 0);
        din31 : IN STD_LOGIC_VECTOR (15 downto 0);
        din32 : IN STD_LOGIC_VECTOR (15 downto 0);
        din33 : IN STD_LOGIC_VECTOR (15 downto 0);
        din34 : IN STD_LOGIC_VECTOR (15 downto 0);
        din35 : IN STD_LOGIC_VECTOR (15 downto 0);
        din36 : IN STD_LOGIC_VECTOR (15 downto 0);
        din37 : IN STD_LOGIC_VECTOR (15 downto 0);
        din38 : IN STD_LOGIC_VECTOR (15 downto 0);
        din39 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_fpga_top_mac_muladd_16s_12s_33s_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (32 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_main5_dense_kernel_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component ecg_fpga_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    main5_dense_kernel_U : component ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_main5_dense_kernel_ROM_AUTO_1R
    generic map (
        DataWidth => 12,
        AddressRange => 960,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => main5_dense_kernel_address0,
        ce0 => main5_dense_kernel_ce0_local,
        q0 => main5_dense_kernel_q0);

    sparsemux_81_6_16_1_1_U52 : component ecg_fpga_top_sparsemux_81_6_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 16,
        CASE1 => "000001",
        din1_WIDTH => 16,
        CASE2 => "000010",
        din2_WIDTH => 16,
        CASE3 => "000011",
        din3_WIDTH => 16,
        CASE4 => "000100",
        din4_WIDTH => 16,
        CASE5 => "000101",
        din5_WIDTH => 16,
        CASE6 => "000110",
        din6_WIDTH => 16,
        CASE7 => "000111",
        din7_WIDTH => 16,
        CASE8 => "001000",
        din8_WIDTH => 16,
        CASE9 => "001001",
        din9_WIDTH => 16,
        CASE10 => "001010",
        din10_WIDTH => 16,
        CASE11 => "001011",
        din11_WIDTH => 16,
        CASE12 => "001100",
        din12_WIDTH => 16,
        CASE13 => "001101",
        din13_WIDTH => 16,
        CASE14 => "001110",
        din14_WIDTH => 16,
        CASE15 => "001111",
        din15_WIDTH => 16,
        CASE16 => "010000",
        din16_WIDTH => 16,
        CASE17 => "010001",
        din17_WIDTH => 16,
        CASE18 => "010010",
        din18_WIDTH => 16,
        CASE19 => "010011",
        din19_WIDTH => 16,
        CASE20 => "010100",
        din20_WIDTH => 16,
        CASE21 => "010101",
        din21_WIDTH => 16,
        CASE22 => "010110",
        din22_WIDTH => 16,
        CASE23 => "010111",
        din23_WIDTH => 16,
        CASE24 => "011000",
        din24_WIDTH => 16,
        CASE25 => "011001",
        din25_WIDTH => 16,
        CASE26 => "011010",
        din26_WIDTH => 16,
        CASE27 => "011011",
        din27_WIDTH => 16,
        CASE28 => "011100",
        din28_WIDTH => 16,
        CASE29 => "011101",
        din29_WIDTH => 16,
        CASE30 => "011110",
        din30_WIDTH => 16,
        CASE31 => "011111",
        din31_WIDTH => 16,
        CASE32 => "100000",
        din32_WIDTH => 16,
        CASE33 => "100001",
        din33_WIDTH => 16,
        CASE34 => "100010",
        din34_WIDTH => 16,
        CASE35 => "100011",
        din35_WIDTH => 16,
        CASE36 => "100100",
        din36_WIDTH => 16,
        CASE37 => "100101",
        din37_WIDTH => 16,
        CASE38 => "100110",
        din38_WIDTH => 16,
        CASE39 => "100111",
        din39_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 6,
        dout_WIDTH => 16)
    port map (
        din0 => in_q12_0_val,
        din1 => in_q12_1_val,
        din2 => in_q12_2_val,
        din3 => in_q12_3_val,
        din4 => in_q12_4_val,
        din5 => in_q12_5_val,
        din6 => in_q12_6_val,
        din7 => in_q12_7_val,
        din8 => in_q12_8_val,
        din9 => in_q12_9_val,
        din10 => in_q12_10_val,
        din11 => in_q12_11_val,
        din12 => in_q12_12_val,
        din13 => in_q12_13_val,
        din14 => in_q12_14_val,
        din15 => in_q12_15_val,
        din16 => in_q12_16_val,
        din17 => in_q12_17_val,
        din18 => in_q12_18_val,
        din19 => in_q12_19_val,
        din20 => in_q12_20_val,
        din21 => in_q12_21_val,
        din22 => in_q12_22_val,
        din23 => in_q12_23_val,
        din24 => in_q12_24_val,
        din25 => in_q12_25_val,
        din26 => in_q12_26_val,
        din27 => in_q12_27_val,
        din28 => in_q12_28_val,
        din29 => in_q12_29_val,
        din30 => in_q12_30_val,
        din31 => in_q12_31_val,
        din32 => in_q12_32_val,
        din33 => in_q12_33_val,
        din34 => in_q12_34_val,
        din35 => in_q12_35_val,
        din36 => in_q12_36_val,
        din37 => in_q12_37_val,
        din38 => in_q12_38_val,
        din39 => in_q12_39_val,
        def => tmp_fu_511_p81,
        sel => ap_sig_allocacmp_i_3,
        dout => tmp_fu_511_p83);

    mac_muladd_16s_12s_33s_33_4_1_U53 : component ecg_fpga_top_mac_muladd_16s_12s_33s_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        din2_WIDTH => 33,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_reg_779_pp0_iter1_reg,
        din1 => main5_dense_kernel_q0,
        din2 => ap_sig_allocacmp_acc_load,
        ce => ap_const_logic_1,
        dout => grp_fu_740_p3);

    flow_control_loop_pipe_sequential_init_U : component ecg_fpga_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    acc_fu_208 <= ap_const_lv33_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    acc_fu_208 <= grp_fu_740_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln61_fu_499_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_212 <= add_ln61_fu_505_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_212 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_3_reg_769 <= ap_sig_allocacmp_i_3;
                icmp_ln61_reg_775 <= icmp_ln61_fu_499_p2;
                icmp_ln61_reg_775_pp0_iter1_reg <= icmp_ln61_reg_775;
                tmp_reg_779 <= tmp_fu_511_p83;
                tmp_reg_779_pp0_iter1_reg <= tmp_reg_779;
                    zext_ln58_cast_reg_764(4 downto 0) <= zext_ln58_cast_fu_482_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln61_reg_775_pp0_iter2_reg <= icmp_ln61_reg_775_pp0_iter1_reg;
                icmp_ln61_reg_775_pp0_iter3_reg <= icmp_ln61_reg_775_pp0_iter2_reg;
            end if;
        end if;
    end process;
    zext_ln58_cast_reg_764(9 downto 5) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_out <= acc_fu_208;

    acc_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln61_reg_775_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln61_reg_775_pp0_iter3_reg = ap_const_lv1_1))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln61_fu_505_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv6_1));
    add_ln63_fu_712_p2 <= std_logic_vector(unsigned(sub_ln63_fu_706_p2) + unsigned(zext_ln58_cast_reg_764));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln61_fu_499_p2)
    begin
        if (((icmp_ln61_fu_499_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0, acc_fu_208, grp_fu_740_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_sig_allocacmp_acc_load <= grp_fu_740_p3;
        else 
            ap_sig_allocacmp_acc_load <= acc_fu_208;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_212)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_212;
        end if; 
    end process;

    icmp_ln61_fu_499_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv6_28) else "0";
    main5_dense_kernel_address0 <= zext_ln64_fu_717_p1(10 - 1 downto 0);

    main5_dense_kernel_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            main5_dense_kernel_ce0_local <= ap_const_logic_1;
        else 
            main5_dense_kernel_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_fu_687_p3 <= (trunc_ln63_fu_684_p1 & ap_const_lv5_0);
    sub_ln63_fu_706_p2 <= std_logic_vector(unsigned(p_shl_fu_687_p3) - unsigned(zext_ln63_fu_702_p1));
    tmp_3_fu_695_p3 <= (i_3_reg_769 & ap_const_lv3_0);
    tmp_fu_511_p81 <= "XXXXXXXXXXXXXXXX";
    trunc_ln63_fu_684_p1 <= i_3_reg_769(5 - 1 downto 0);
    zext_ln58_cast_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln58),10));
    zext_ln63_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_695_p3),10));
    zext_ln64_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_fu_712_p2),64));
end behav;
