-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_fpga_top_extract_light_features_40_int is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    beat_in_q12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    beat_in_q12_ce0 : OUT STD_LOGIC;
    beat_in_q12_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_0_ap_vld : OUT STD_LOGIC;
    feat_q12_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_1_ap_vld : OUT STD_LOGIC;
    feat_q12_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_2_ap_vld : OUT STD_LOGIC;
    feat_q12_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_3_ap_vld : OUT STD_LOGIC;
    feat_q12_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_4_ap_vld : OUT STD_LOGIC;
    feat_q12_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_5_ap_vld : OUT STD_LOGIC;
    feat_q12_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_6_ap_vld : OUT STD_LOGIC;
    feat_q12_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_7_ap_vld : OUT STD_LOGIC;
    feat_q12_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_8_ap_vld : OUT STD_LOGIC;
    feat_q12_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_9_ap_vld : OUT STD_LOGIC;
    feat_q12_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_10_ap_vld : OUT STD_LOGIC;
    feat_q12_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_11_ap_vld : OUT STD_LOGIC;
    feat_q12_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_12_ap_vld : OUT STD_LOGIC;
    feat_q12_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_13_ap_vld : OUT STD_LOGIC;
    feat_q12_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_14_ap_vld : OUT STD_LOGIC;
    feat_q12_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_15_ap_vld : OUT STD_LOGIC;
    feat_q12_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_16_ap_vld : OUT STD_LOGIC;
    feat_q12_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_17_ap_vld : OUT STD_LOGIC;
    feat_q12_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_18_ap_vld : OUT STD_LOGIC;
    feat_q12_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_19_ap_vld : OUT STD_LOGIC;
    feat_q12_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_20_ap_vld : OUT STD_LOGIC;
    feat_q12_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_21_ap_vld : OUT STD_LOGIC;
    feat_q12_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_22_ap_vld : OUT STD_LOGIC;
    feat_q12_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_23_ap_vld : OUT STD_LOGIC;
    feat_q12_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_24_ap_vld : OUT STD_LOGIC;
    feat_q12_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_25_ap_vld : OUT STD_LOGIC;
    feat_q12_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_26_ap_vld : OUT STD_LOGIC;
    feat_q12_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_27_ap_vld : OUT STD_LOGIC;
    feat_q12_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_28_ap_vld : OUT STD_LOGIC;
    feat_q12_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_29_ap_vld : OUT STD_LOGIC;
    feat_q12_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_30_ap_vld : OUT STD_LOGIC;
    feat_q12_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_31_ap_vld : OUT STD_LOGIC;
    feat_q12_32 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_32_ap_vld : OUT STD_LOGIC;
    feat_q12_33 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_33_ap_vld : OUT STD_LOGIC;
    feat_q12_34 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_34_ap_vld : OUT STD_LOGIC;
    feat_q12_35 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_35_ap_vld : OUT STD_LOGIC;
    feat_q12_36 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_36_ap_vld : OUT STD_LOGIC;
    feat_q12_37 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_37_ap_vld : OUT STD_LOGIC;
    feat_q12_38 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_38_ap_vld : OUT STD_LOGIC;
    feat_q12_39 : OUT STD_LOGIC_VECTOR (15 downto 0);
    feat_q12_39_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_fpga_top_extract_light_features_40_int is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv65_111111112 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000100010001000100010001000100010010";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_77FFF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000001110111111111111111";
    constant ap_const_lv32_FFF87FF2 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111110000111111111110010";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv65_0 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal c_1_reg_776 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln24_fu_512_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln24_reg_783 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln_fu_518_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_reg_788 : STD_LOGIC_VECTOR (8 downto 0);
    signal prev_reg_798 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_2_reg_808 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_reg_814 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_820 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_493_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal mul_ln46_reg_825 : STD_LOGIC_VECTOR (64 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_1_cast_reg_830 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_idle : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_ready : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0 : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out_ap_vld : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out_ap_vld : STD_LOGIC;
    signal grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln27_fu_526_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln24_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_178 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal select_ln45_fu_612_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_predicate_pred215_state8 : BOOLEAN;
    signal select_ln6_1_fu_684_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_predicate_pred221_state8 : BOOLEAN;
    signal ap_predicate_pred226_state8 : BOOLEAN;
    signal ap_predicate_pred231_state8 : BOOLEAN;
    signal ap_predicate_pred236_state8 : BOOLEAN;
    signal ap_predicate_pred241_state8 : BOOLEAN;
    signal ap_predicate_pred246_state8 : BOOLEAN;
    signal ap_predicate_pred251_state8 : BOOLEAN;
    signal ap_predicate_pred256_state8 : BOOLEAN;
    signal ap_predicate_pred261_state8 : BOOLEAN;
    signal ap_predicate_pred266_state8 : BOOLEAN;
    signal ap_predicate_pred271_state8 : BOOLEAN;
    signal ap_predicate_pred276_state8 : BOOLEAN;
    signal ap_predicate_pred281_state8 : BOOLEAN;
    signal ap_predicate_pred286_state8 : BOOLEAN;
    signal ap_predicate_pred291_state8 : BOOLEAN;
    signal ap_predicate_pred296_state8 : BOOLEAN;
    signal ap_predicate_pred301_state8 : BOOLEAN;
    signal ap_predicate_pred305_state8 : BOOLEAN;
    signal ap_predicate_pred345_state8 : BOOLEAN;
    signal beat_in_q12_ce0_local : STD_LOGIC;
    signal grp_fu_493_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln46_fu_534_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_539_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln6_fu_547_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln7_fu_553_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln45_fu_580_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln45_1_fu_586_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_572_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln45_1_fu_596_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln45_2_fu_602_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln46_fu_640_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_cast_fu_645_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln8_fu_655_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln8_fu_661_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln6_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln6_fu_673_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln46_fu_667_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        prev : IN STD_LOGIC_VECTOR (15 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (8 downto 0);
        beat_in_q12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        beat_in_q12_ce0 : OUT STD_LOGIC;
        beat_in_q12_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        sum_out : OUT STD_LOGIC_VECTOR (19 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC;
        diff_sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        diff_sum_out_ap_vld : OUT STD_LOGIC );
    end component;


    component ecg_fpga_top_mul_32s_34ns_65_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (64 downto 0) );
    end component;



begin
    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483 : component ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start,
        ap_done => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done,
        ap_idle => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_idle,
        ap_ready => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_ready,
        prev => prev_reg_798,
        shl_ln => shl_ln_reg_788,
        beat_in_q12_address0 => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0,
        beat_in_q12_ce0 => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0,
        beat_in_q12_q0 => beat_in_q12_q0,
        sum_out => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out,
        sum_out_ap_vld => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out_ap_vld,
        diff_sum_out => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out,
        diff_sum_out_ap_vld => grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out_ap_vld);

    mul_32s_34ns_65_2_1_U9 : component ecg_fpga_top_mul_32s_34ns_65_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln46_fu_534_p0,
        din1 => grp_fu_493_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_493_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_ready = ap_const_logic_1)) then 
                    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                c_fu_178 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                c_fu_178 <= add_ln24_reg_783;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln24_reg_783 <= add_ln24_fu_512_p2;
                c_1_reg_776 <= c_fu_178;
                    shl_ln_reg_788(8 downto 4) <= shl_ln_fu_518_p3(8 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                    ap_predicate_pred215_state8 <= (c_1_reg_776 = ap_const_lv5_12);
                    ap_predicate_pred221_state8 <= (c_1_reg_776 = ap_const_lv5_11);
                    ap_predicate_pred226_state8 <= (c_1_reg_776 = ap_const_lv5_10);
                    ap_predicate_pred231_state8 <= (c_1_reg_776 = ap_const_lv5_F);
                    ap_predicate_pred236_state8 <= (c_1_reg_776 = ap_const_lv5_E);
                    ap_predicate_pred241_state8 <= (c_1_reg_776 = ap_const_lv5_D);
                    ap_predicate_pred246_state8 <= (c_1_reg_776 = ap_const_lv5_C);
                    ap_predicate_pred251_state8 <= (c_1_reg_776 = ap_const_lv5_B);
                    ap_predicate_pred256_state8 <= (c_1_reg_776 = ap_const_lv5_A);
                    ap_predicate_pred261_state8 <= (c_1_reg_776 = ap_const_lv5_9);
                    ap_predicate_pred266_state8 <= (c_1_reg_776 = ap_const_lv5_8);
                    ap_predicate_pred271_state8 <= (c_1_reg_776 = ap_const_lv5_7);
                    ap_predicate_pred276_state8 <= (c_1_reg_776 = ap_const_lv5_6);
                    ap_predicate_pred281_state8 <= (c_1_reg_776 = ap_const_lv5_5);
                    ap_predicate_pred286_state8 <= (c_1_reg_776 = ap_const_lv5_4);
                    ap_predicate_pred291_state8 <= (c_1_reg_776 = ap_const_lv5_3);
                    ap_predicate_pred296_state8 <= (c_1_reg_776 = ap_const_lv5_2);
                    ap_predicate_pred301_state8 <= (c_1_reg_776 = ap_const_lv5_1);
                    ap_predicate_pred305_state8 <= (c_1_reg_776 = ap_const_lv5_0);
                    ap_predicate_pred345_state8 <= (not((c_1_reg_776 = ap_const_lv5_0)) and not((c_1_reg_776 = ap_const_lv5_1)) and not((c_1_reg_776 = ap_const_lv5_2)) and not((c_1_reg_776 = ap_const_lv5_3)) and not((c_1_reg_776 = ap_const_lv5_4)) and not((c_1_reg_776 = ap_const_lv5_5)) and not((c_1_reg_776 = ap_const_lv5_6)) and not((c_1_reg_776 = ap_const_lv5_7)) and not((c_1_reg_776 = ap_const_lv5_8)) and not((c_1_reg_776 = ap_const_lv5_9)) and not((c_1_reg_776 = ap_const_lv5_A)) and not((c_1_reg_776 = ap_const_lv5_B)) and not((c_1_reg_776 = ap_const_lv5_C)) and not((c_1_reg_776 = ap_const_lv5_D)) and not((c_1_reg_776 = ap_const_lv5_E)) and not((c_1_reg_776 = ap_const_lv5_F)) and not((c_1_reg_776 = ap_const_lv5_10)) and not((c_1_reg_776 = ap_const_lv5_11)) and not((c_1_reg_776 = ap_const_lv5_12)));
                mul_ln46_reg_825 <= grp_fu_493_p2;
                tmp_1_cast_reg_830 <= grp_fu_493_p2(51 downto 36);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_ln6_reg_814 <= icmp_ln6_fu_547_p2;
                icmp_ln7_reg_820 <= icmp_ln7_fu_553_p2;
                tmp_2_reg_808 <= tmp_2_fu_539_p1(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                prev_reg_798 <= beat_in_q12_q0;
            end if;
        end if;
    end process;
    shl_ln_reg_788(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done, ap_CS_fsm_state5, icmp_ln24_fu_506_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln24_fu_506_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln24_fu_512_p2 <= std_logic_vector(unsigned(c_fu_178) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done)
    begin
        if ((grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln24_fu_506_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln24_fu_506_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln24_fu_506_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln24_fu_506_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    beat_in_q12_address0_assign_proc : process(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0, ap_CS_fsm_state5, zext_ln27_fu_526_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            beat_in_q12_address0 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0;
        else 
            beat_in_q12_address0 <= zext_ln27_fu_526_p1(9 - 1 downto 0);
        end if; 
    end process;


    beat_in_q12_ce0_assign_proc : process(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0, ap_CS_fsm_state5, beat_in_q12_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            beat_in_q12_ce0 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0;
        else 
            beat_in_q12_ce0 <= beat_in_q12_ce0_local;
        end if; 
    end process;


    beat_in_q12_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            beat_in_q12_ce0_local <= ap_const_logic_1;
        else 
            beat_in_q12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_0 <= select_ln45_fu_612_p3;

    feat_q12_0_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred305_state8)
    begin
        if (((ap_predicate_pred305_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_0_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_1 <= select_ln45_fu_612_p3;
    feat_q12_10 <= select_ln45_fu_612_p3;

    feat_q12_10_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred256_state8)
    begin
        if (((ap_predicate_pred256_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_10_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_11 <= select_ln45_fu_612_p3;

    feat_q12_11_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred251_state8)
    begin
        if (((ap_predicate_pred251_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_11_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_12 <= select_ln45_fu_612_p3;

    feat_q12_12_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred246_state8)
    begin
        if (((ap_predicate_pred246_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_12_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_13 <= select_ln45_fu_612_p3;

    feat_q12_13_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred241_state8)
    begin
        if (((ap_predicate_pred241_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_13_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_14 <= select_ln45_fu_612_p3;

    feat_q12_14_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred236_state8)
    begin
        if (((ap_predicate_pred236_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_14_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_15 <= select_ln45_fu_612_p3;

    feat_q12_15_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred231_state8)
    begin
        if (((ap_predicate_pred231_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_15_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_16 <= select_ln45_fu_612_p3;

    feat_q12_16_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred226_state8)
    begin
        if (((ap_predicate_pred226_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_16_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_17 <= select_ln45_fu_612_p3;

    feat_q12_17_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred221_state8)
    begin
        if (((ap_predicate_pred221_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_17_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_18 <= select_ln45_fu_612_p3;

    feat_q12_18_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred215_state8)
    begin
        if (((ap_predicate_pred215_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_18_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_19 <= select_ln45_fu_612_p3;

    feat_q12_19_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred345_state8)
    begin
        if (((ap_predicate_pred345_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_19_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_19_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    feat_q12_1_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred301_state8)
    begin
        if (((ap_predicate_pred301_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_1_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_2 <= select_ln45_fu_612_p3;
    feat_q12_20 <= select_ln6_1_fu_684_p3;

    feat_q12_20_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred305_state8)
    begin
        if (((ap_predicate_pred305_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_20_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_20_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_21 <= select_ln6_1_fu_684_p3;

    feat_q12_21_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred301_state8)
    begin
        if (((ap_predicate_pred301_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_21_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_21_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_22 <= select_ln6_1_fu_684_p3;

    feat_q12_22_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred296_state8)
    begin
        if (((ap_predicate_pred296_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_22_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_22_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_23 <= select_ln6_1_fu_684_p3;

    feat_q12_23_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred291_state8)
    begin
        if (((ap_predicate_pred291_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_23_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_23_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_24 <= select_ln6_1_fu_684_p3;

    feat_q12_24_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred286_state8)
    begin
        if (((ap_predicate_pred286_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_24_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_24_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_25 <= select_ln6_1_fu_684_p3;

    feat_q12_25_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred281_state8)
    begin
        if (((ap_predicate_pred281_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_25_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_25_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_26 <= select_ln6_1_fu_684_p3;

    feat_q12_26_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred276_state8)
    begin
        if (((ap_predicate_pred276_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_26_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_26_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_27 <= select_ln6_1_fu_684_p3;

    feat_q12_27_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred271_state8)
    begin
        if (((ap_predicate_pred271_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_27_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_27_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_28 <= select_ln6_1_fu_684_p3;

    feat_q12_28_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred266_state8)
    begin
        if (((ap_predicate_pred266_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_28_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_28_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_29 <= select_ln6_1_fu_684_p3;

    feat_q12_29_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred261_state8)
    begin
        if (((ap_predicate_pred261_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_29_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_29_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    feat_q12_2_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred296_state8)
    begin
        if (((ap_predicate_pred296_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_2_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_3 <= select_ln45_fu_612_p3;
    feat_q12_30 <= select_ln6_1_fu_684_p3;

    feat_q12_30_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred256_state8)
    begin
        if (((ap_predicate_pred256_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_30_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_30_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_31 <= select_ln6_1_fu_684_p3;

    feat_q12_31_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred251_state8)
    begin
        if (((ap_predicate_pred251_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_31_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_31_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_32 <= select_ln6_1_fu_684_p3;

    feat_q12_32_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred246_state8)
    begin
        if (((ap_predicate_pred246_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_32_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_32_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_33 <= select_ln6_1_fu_684_p3;

    feat_q12_33_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred241_state8)
    begin
        if (((ap_predicate_pred241_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_33_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_33_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_34 <= select_ln6_1_fu_684_p3;

    feat_q12_34_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred236_state8)
    begin
        if (((ap_predicate_pred236_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_34_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_34_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_35 <= select_ln6_1_fu_684_p3;

    feat_q12_35_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred231_state8)
    begin
        if (((ap_predicate_pred231_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_35_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_35_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_36 <= select_ln6_1_fu_684_p3;

    feat_q12_36_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred226_state8)
    begin
        if (((ap_predicate_pred226_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_36_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_36_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_37 <= select_ln6_1_fu_684_p3;

    feat_q12_37_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred221_state8)
    begin
        if (((ap_predicate_pred221_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_37_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_37_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_38 <= select_ln6_1_fu_684_p3;

    feat_q12_38_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred215_state8)
    begin
        if (((ap_predicate_pred215_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_38_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_38_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_39 <= select_ln6_1_fu_684_p3;

    feat_q12_39_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred345_state8)
    begin
        if (((ap_predicate_pred345_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_39_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_39_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    feat_q12_3_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred291_state8)
    begin
        if (((ap_predicate_pred291_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_3_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_4 <= select_ln45_fu_612_p3;

    feat_q12_4_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred286_state8)
    begin
        if (((ap_predicate_pred286_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_4_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_5 <= select_ln45_fu_612_p3;

    feat_q12_5_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred281_state8)
    begin
        if (((ap_predicate_pred281_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_5_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_6 <= select_ln45_fu_612_p3;

    feat_q12_6_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred276_state8)
    begin
        if (((ap_predicate_pred276_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_6_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_7 <= select_ln45_fu_612_p3;

    feat_q12_7_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred271_state8)
    begin
        if (((ap_predicate_pred271_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_7_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_8 <= select_ln45_fu_612_p3;

    feat_q12_8_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred266_state8)
    begin
        if (((ap_predicate_pred266_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_8_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    feat_q12_9 <= select_ln45_fu_612_p3;

    feat_q12_9_ap_vld_assign_proc : process(ap_CS_fsm_state8, ap_predicate_pred261_state8)
    begin
        if (((ap_predicate_pred261_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            feat_q12_9_ap_vld <= ap_const_logic_1;
        else 
            feat_q12_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg;
    grp_fu_493_p1 <= ap_const_lv65_111111112(34 - 1 downto 0);
    icmp_ln24_fu_506_p2 <= "1" when (c_fu_178 = ap_const_lv5_14) else "0";
    icmp_ln6_fu_547_p0 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;
    icmp_ln6_fu_547_p2 <= "1" when (signed(icmp_ln6_fu_547_p0) > signed(ap_const_lv32_77FFF)) else "0";
    icmp_ln7_fu_553_p0 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;
    icmp_ln7_fu_553_p2 <= "1" when (signed(icmp_ln7_fu_553_p0) < signed(ap_const_lv32_FFF87FF2)) else "0";
    or_ln6_fu_680_p2 <= (icmp_ln7_reg_820 or icmp_ln6_reg_814);
    select_ln45_fu_612_p3 <= 
        sub_ln45_1_fu_596_p2 when (tmp_fu_572_p3(0) = '1') else 
        trunc_ln45_2_fu_602_p4;
    select_ln46_fu_667_p3 <= 
        sub_ln8_fu_661_p2 when (tmp_2_reg_808(0) = '1') else 
        tmp_1_cast_reg_830;
    select_ln6_1_fu_684_p3 <= 
        select_ln6_fu_673_p3 when (or_ln6_fu_680_p2(0) = '1') else 
        select_ln46_fu_667_p3;
    select_ln6_fu_673_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln6_reg_814(0) = '1') else 
        ap_const_lv16_8000;
    select_ln8_fu_655_p3 <= 
        tmp_cast_fu_645_p4 when (tmp_2_reg_808(0) = '1') else 
        tmp_1_cast_reg_830;
    sext_ln46_fu_534_p0 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;
    shl_ln_fu_518_p3 <= (c_fu_178 & ap_const_lv4_0);
    sub_ln45_1_fu_596_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln45_1_fu_586_p4));
    sub_ln45_fu_580_p2 <= std_logic_vector(unsigned(ap_const_lv20_0) - unsigned(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out));
    sub_ln46_fu_640_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln46_reg_825));
    sub_ln8_fu_661_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(select_ln8_fu_655_p3));
    tmp_2_fu_539_p1 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;
    tmp_cast_fu_645_p4 <= sub_ln46_fu_640_p2(51 downto 36);
    tmp_fu_572_p3 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out(19 downto 19);
    trunc_ln45_1_fu_586_p4 <= sub_ln45_fu_580_p2(19 downto 4);
    trunc_ln45_2_fu_602_p4 <= grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out(19 downto 4);
    zext_ln27_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_518_p3),64));
end behav;
