-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_fpga_top_dense_24x5_linear_int is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_q12_0_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_1_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_2_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_3_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_4_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_5_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_6_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_7_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_8_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_9_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_10_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_11_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_12_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_13_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_14_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_15_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_16_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_17_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_18_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_19_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_20_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_21_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_22_val : IN STD_LOGIC_VECTOR (14 downto 0);
    in_q12_23_val : IN STD_LOGIC_VECTOR (14 downto 0);
    out_q12_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_q12_0_ap_vld : OUT STD_LOGIC;
    out_q12_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_q12_1_ap_vld : OUT STD_LOGIC;
    out_q12_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_q12_2_ap_vld : OUT STD_LOGIC;
    out_q12_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_q12_3_ap_vld : OUT STD_LOGIC;
    out_q12_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_q12_4_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_fpga_top_dense_24x5_linear_int is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv21_1F8000 : STD_LOGIC_VECTOR (20 downto 0) := "111111000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal main5_class_output_bias_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal main5_class_output_bias_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal o_2_reg_603 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln81_fu_363_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln81_reg_610 : STD_LOGIC_VECTOR (2 downto 0);
    signal acc_fu_374_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal acc_reg_620 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start : STD_LOGIC;
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done : STD_LOGIC;
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_idle : STD_LOGIC;
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_ready : STD_LOGIC;
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out_ap_vld : STD_LOGIC;
    signal grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln81_fu_369_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln81_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal o_fu_116 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln6_fu_442_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal main5_class_output_bias_ce0_local : STD_LOGIC;
    signal tmp_fu_396_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln_fu_386_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln6_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln6_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln6_3_fu_428_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln8_fu_418_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln82 : IN STD_LOGIC_VECTOR (25 downto 0);
        zext_ln81_1 : IN STD_LOGIC_VECTOR (2 downto 0);
        in_q12_0_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_1_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_2_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_3_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_4_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_5_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_6_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_7_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_8_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_9_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_10_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_11_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_12_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_13_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_14_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_15_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_16_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_17_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_18_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_19_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_20_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_21_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_22_val : IN STD_LOGIC_VECTOR (14 downto 0);
        in_q12_23_val : IN STD_LOGIC_VECTOR (14 downto 0);
        acc_2_out : OUT STD_LOGIC_VECTOR (32 downto 0);
        acc_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component ecg_fpga_top_dense_24x5_linear_int_main5_class_output_bias_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    main5_class_output_bias_U : component ecg_fpga_top_dense_24x5_linear_int_main5_class_output_bias_ROM_AUTO_1R
    generic map (
        DataWidth => 14,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => main5_class_output_bias_address0,
        ce0 => main5_class_output_bias_ce0_local,
        q0 => main5_class_output_bias_q0);

    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316 : component ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start,
        ap_done => grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done,
        ap_idle => grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_idle,
        ap_ready => grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_ready,
        sext_ln82 => acc_reg_620,
        zext_ln81_1 => o_fu_116,
        in_q12_0_val => in_q12_0_val,
        in_q12_1_val => in_q12_1_val,
        in_q12_2_val => in_q12_2_val,
        in_q12_3_val => in_q12_3_val,
        in_q12_4_val => in_q12_4_val,
        in_q12_5_val => in_q12_5_val,
        in_q12_6_val => in_q12_6_val,
        in_q12_7_val => in_q12_7_val,
        in_q12_8_val => in_q12_8_val,
        in_q12_9_val => in_q12_9_val,
        in_q12_10_val => in_q12_10_val,
        in_q12_11_val => in_q12_11_val,
        in_q12_12_val => in_q12_12_val,
        in_q12_13_val => in_q12_13_val,
        in_q12_14_val => in_q12_14_val,
        in_q12_15_val => in_q12_15_val,
        in_q12_16_val => in_q12_16_val,
        in_q12_17_val => in_q12_17_val,
        in_q12_18_val => in_q12_18_val,
        in_q12_19_val => in_q12_19_val,
        in_q12_20_val => in_q12_20_val,
        in_q12_21_val => in_q12_21_val,
        in_q12_22_val => in_q12_22_val,
        in_q12_23_val => in_q12_23_val,
        acc_2_out => grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out,
        acc_2_out_ap_vld => grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_ready = ap_const_logic_1)) then 
                    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    o_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                o_fu_116 <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                o_fu_116 <= add_ln81_reg_610;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    acc_reg_620(25 downto 12) <= acc_fu_374_p3(25 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln81_reg_610 <= add_ln81_fu_363_p2;
                o_2_reg_603 <= o_fu_116;
            end if;
        end if;
    end process;
    acc_reg_620(11 downto 0) <= "000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done, ap_CS_fsm_state4, icmp_ln81_fu_357_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_357_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    acc_fu_374_p3 <= (main5_class_output_bias_q0 & ap_const_lv12_0);
    add_ln81_fu_363_p2 <= std_logic_vector(unsigned(o_fu_116) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done)
    begin
        if ((grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln81_fu_357_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_357_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln81_fu_357_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_357_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start <= grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg;
    icmp_ln6_fu_406_p2 <= "1" when (signed(tmp_fu_396_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln7_fu_412_p2 <= "1" when (signed(trunc_ln_fu_386_p4) < signed(ap_const_lv21_1F8000)) else "0";
    icmp_ln81_fu_357_p2 <= "1" when (o_fu_116 = ap_const_lv3_5) else "0";
    main5_class_output_bias_address0 <= zext_ln81_fu_369_p1(3 - 1 downto 0);

    main5_class_output_bias_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            main5_class_output_bias_ce0_local <= ap_const_logic_1;
        else 
            main5_class_output_bias_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln6_fu_436_p2 <= (icmp_ln7_fu_412_p2 or icmp_ln6_fu_406_p2);
    out_q12_0 <= select_ln6_fu_442_p3;

    out_q12_0_ap_vld_assign_proc : process(o_2_reg_603, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (o_2_reg_603 = ap_const_lv3_0))) then 
            out_q12_0_ap_vld <= ap_const_logic_1;
        else 
            out_q12_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_q12_1 <= select_ln6_fu_442_p3;

    out_q12_1_ap_vld_assign_proc : process(o_2_reg_603, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (o_2_reg_603 = ap_const_lv3_1))) then 
            out_q12_1_ap_vld <= ap_const_logic_1;
        else 
            out_q12_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_q12_2 <= select_ln6_fu_442_p3;

    out_q12_2_ap_vld_assign_proc : process(o_2_reg_603, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (o_2_reg_603 = ap_const_lv3_2))) then 
            out_q12_2_ap_vld <= ap_const_logic_1;
        else 
            out_q12_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_q12_3 <= select_ln6_fu_442_p3;

    out_q12_3_ap_vld_assign_proc : process(o_2_reg_603, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (o_2_reg_603 = ap_const_lv3_3))) then 
            out_q12_3_ap_vld <= ap_const_logic_1;
        else 
            out_q12_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_q12_4 <= select_ln6_fu_442_p3;

    out_q12_4_ap_vld_assign_proc : process(o_2_reg_603, ap_CS_fsm_state5)
    begin
        if ((not((o_2_reg_603 = ap_const_lv3_0)) and not((o_2_reg_603 = ap_const_lv3_1)) and not((o_2_reg_603 = ap_const_lv3_2)) and not((o_2_reg_603 = ap_const_lv3_3)) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_q12_4_ap_vld <= ap_const_logic_1;
        else 
            out_q12_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln6_3_fu_428_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln6_fu_406_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln6_fu_442_p3 <= 
        select_ln6_3_fu_428_p3 when (or_ln6_fu_436_p2(0) = '1') else 
        trunc_ln8_fu_418_p4;
    tmp_fu_396_p4 <= grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out(32 downto 27);
    trunc_ln8_fu_418_p4 <= grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out(27 downto 12);
    trunc_ln_fu_386_p4 <= grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out(32 downto 12);
    zext_ln81_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(o_fu_116),64));
end behav;
