-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_fpga_top_dense_40x24_relu_int_p_ZL18main5_dense_kernel_5_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 24
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_fpga_top_dense_40x24_relu_int_p_ZL18main5_dense_kernel_5_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000011111101", 1 => "111000011010", 2 => "001101000011", 3 => "111010010101", 
    4 => "000100001100", 5 => "000111010111", 6 => "000001101111", 7 => "101010111110", 
    8 => "000011111101", 9 => "111110110100", 10 => "000101110001", 11 => "111111110100", 
    12 => "000000111100", 13 => "111010011101", 14 => "000000100111", 15 => "111011001010", 
    16 => "000000101001", 17 => "101111111100", 18 => "000000001100", 19 => "111111010000", 
    20 => "111101100000", 21 => "110110101001", 22 => "111100101000", 23 => "000001111010");

signal mem1 : mem_array := (
    0 => "000011111101", 1 => "111000011010", 2 => "001101000011", 3 => "111010010101", 
    4 => "000100001100", 5 => "000111010111", 6 => "000001101111", 7 => "101010111110", 
    8 => "000011111101", 9 => "111110110100", 10 => "000101110001", 11 => "111111110100", 
    12 => "000000111100", 13 => "111010011101", 14 => "000000100111", 15 => "111011001010", 
    16 => "000000101001", 17 => "101111111100", 18 => "000000001100", 19 => "111111010000", 
    20 => "111101100000", 21 => "110110101001", 22 => "111100101000", 23 => "000001111010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;

end if;
end process;

end rtl;

