// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_ecg_fpga_top_Pipeline_VITIS_LOOP_137_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        best_val,
        score_q12_1_load,
        score_q12_2_load,
        score_q12_3_load,
        score_q12_4_load,
        best_idx_out,
        best_idx_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] best_val;
input  [15:0] score_q12_1_load;
input  [15:0] score_q12_2_load;
input  [15:0] score_q12_3_load;
input  [15:0] score_q12_4_load;
output  [31:0] best_idx_out;
output   best_idx_out_ap_vld;

reg ap_idle;
reg best_idx_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln137_fu_115_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_reg_221;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] tmp_fu_121_p11;
reg   [15:0] tmp_reg_229;
reg   [15:0] best_val_1_fu_48;
wire   [15:0] best_val_2_fu_167_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [31:0] best_idx_fu_52;
wire   [31:0] best_idx_1_fu_177_p3;
reg   [2:0] i_1_fu_56;
wire   [2:0] add_ln137_fu_145_p2;
reg   [2:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] tmp_fu_121_p9;
wire   [0:0] icmp_ln138_fu_162_p2;
wire   [31:0] zext_ln138_fu_174_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_121_p1;
wire   [2:0] tmp_fu_121_p3;
wire   [2:0] tmp_fu_121_p5;
wire  signed [2:0] tmp_fu_121_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 best_val_1_fu_48 = 16'd0;
#0 best_idx_fu_52 = 32'd0;
#0 i_1_fu_56 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ecg_fpga_top_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U424(
    .din0(score_q12_1_load),
    .din1(score_q12_2_load),
    .din2(score_q12_3_load),
    .din3(score_q12_4_load),
    .def(tmp_fu_121_p9),
    .sel(ap_sig_allocacmp_i),
    .dout(tmp_fu_121_p11)
);

ecg_fpga_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            best_idx_fu_52 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            best_idx_fu_52 <= best_idx_1_fu_177_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            best_val_1_fu_48 <= best_val;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            best_val_1_fu_48 <= best_val_2_fu_167_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln137_fu_115_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_56 <= add_ln137_fu_145_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_56 <= 3'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_221 <= ap_sig_allocacmp_i;
        tmp_reg_229 <= tmp_fu_121_p11;
    end
end

always @ (*) begin
    if (((icmp_ln137_fu_115_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 3'd1;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_56;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln137_fu_115_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        best_idx_out_ap_vld = 1'b1;
    end else begin
        best_idx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln137_fu_145_p2 = (ap_sig_allocacmp_i + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign best_idx_1_fu_177_p3 = ((icmp_ln138_fu_162_p2[0:0] == 1'b1) ? zext_ln138_fu_174_p1 : best_idx_fu_52);

assign best_idx_out = best_idx_fu_52;

assign best_val_2_fu_167_p3 = ((icmp_ln138_fu_162_p2[0:0] == 1'b1) ? tmp_reg_229 : best_val_1_fu_48);

assign icmp_ln137_fu_115_p2 = ((ap_sig_allocacmp_i == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_162_p2 = (($signed(tmp_reg_229) > $signed(best_val_1_fu_48)) ? 1'b1 : 1'b0);

assign tmp_fu_121_p9 = 'bx;

assign zext_ln138_fu_174_p1 = i_reg_221;

endmodule //ecg_fpga_top_ecg_fpga_top_Pipeline_VITIS_LOOP_137_1
