// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln82,
        zext_ln81_1,
        in_q12_0_val,
        in_q12_1_val,
        in_q12_2_val,
        in_q12_3_val,
        in_q12_4_val,
        in_q12_5_val,
        in_q12_6_val,
        in_q12_7_val,
        in_q12_8_val,
        in_q12_9_val,
        in_q12_10_val,
        in_q12_11_val,
        in_q12_12_val,
        in_q12_13_val,
        in_q12_14_val,
        in_q12_15_val,
        in_q12_16_val,
        in_q12_17_val,
        in_q12_18_val,
        in_q12_19_val,
        in_q12_20_val,
        in_q12_21_val,
        in_q12_22_val,
        in_q12_23_val,
        acc_2_out,
        acc_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [25:0] sext_ln82;
input  [2:0] zext_ln81_1;
input  [14:0] in_q12_0_val;
input  [14:0] in_q12_1_val;
input  [14:0] in_q12_2_val;
input  [14:0] in_q12_3_val;
input  [14:0] in_q12_4_val;
input  [14:0] in_q12_5_val;
input  [14:0] in_q12_6_val;
input  [14:0] in_q12_7_val;
input  [14:0] in_q12_8_val;
input  [14:0] in_q12_9_val;
input  [14:0] in_q12_10_val;
input  [14:0] in_q12_11_val;
input  [14:0] in_q12_12_val;
input  [14:0] in_q12_13_val;
input  [14:0] in_q12_14_val;
input  [14:0] in_q12_15_val;
input  [14:0] in_q12_16_val;
input  [14:0] in_q12_17_val;
input  [14:0] in_q12_18_val;
input  [14:0] in_q12_19_val;
input  [14:0] in_q12_20_val;
input  [14:0] in_q12_21_val;
input  [14:0] in_q12_22_val;
input  [14:0] in_q12_23_val;
output  [32:0] acc_2_out;
output   acc_2_out_ap_vld;

reg ap_idle;
reg acc_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln84_fu_347_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] main5_class_output_kernel_address0;
wire  signed [13:0] main5_class_output_kernel_q0;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] zext_ln81_1_cast_fu_326_p1;
reg   [6:0] zext_ln81_1_cast_reg_536;
reg   [4:0] i_4_reg_541;
reg   [0:0] icmp_ln84_reg_547;
reg   [0:0] icmp_ln84_reg_547_pp0_iter1_reg;
reg   [0:0] icmp_ln84_reg_547_pp0_iter2_reg;
reg   [0:0] icmp_ln84_reg_547_pp0_iter3_reg;
wire   [14:0] tmp_cast_fu_359_p51;
reg   [14:0] tmp_cast_reg_551;
reg   [14:0] tmp_cast_reg_551_pp0_iter1_reg;
wire   [63:0] zext_ln87_fu_489_p1;
wire    ap_block_pp0_stage0;
reg   [32:0] acc_fu_142;
wire  signed [32:0] grp_fu_512_p3;
wire  signed [32:0] sext_ln82_cast_fu_330_p1;
reg  signed [32:0] ap_sig_allocacmp_acc_load_2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [4:0] i_fu_146;
wire   [4:0] add_ln84_fu_353_p2;
reg   [4:0] ap_sig_allocacmp_i_4;
wire    ap_block_pp0_stage0_01001;
reg    main5_class_output_kernel_ce0_local;
wire   [14:0] tmp_cast_fu_359_p49;
wire   [6:0] p_shl_fu_471_p3;
wire   [6:0] zext_ln86_fu_468_p1;
wire   [6:0] add_ln86_1_fu_478_p2;
wire   [6:0] add_ln86_fu_484_p2;
wire   [14:0] grp_fu_512_p0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [28:0] grp_fu_512_p00;
wire   [4:0] tmp_cast_fu_359_p1;
wire   [4:0] tmp_cast_fu_359_p3;
wire   [4:0] tmp_cast_fu_359_p5;
wire   [4:0] tmp_cast_fu_359_p7;
wire   [4:0] tmp_cast_fu_359_p9;
wire   [4:0] tmp_cast_fu_359_p11;
wire   [4:0] tmp_cast_fu_359_p13;
wire   [4:0] tmp_cast_fu_359_p15;
wire   [4:0] tmp_cast_fu_359_p17;
wire   [4:0] tmp_cast_fu_359_p19;
wire   [4:0] tmp_cast_fu_359_p21;
wire   [4:0] tmp_cast_fu_359_p23;
wire   [4:0] tmp_cast_fu_359_p25;
wire   [4:0] tmp_cast_fu_359_p27;
wire   [4:0] tmp_cast_fu_359_p29;
wire   [4:0] tmp_cast_fu_359_p31;
wire  signed [4:0] tmp_cast_fu_359_p33;
wire  signed [4:0] tmp_cast_fu_359_p35;
wire  signed [4:0] tmp_cast_fu_359_p37;
wire  signed [4:0] tmp_cast_fu_359_p39;
wire  signed [4:0] tmp_cast_fu_359_p41;
wire  signed [4:0] tmp_cast_fu_359_p43;
wire  signed [4:0] tmp_cast_fu_359_p45;
wire  signed [4:0] tmp_cast_fu_359_p47;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 acc_fu_142 = 33'd0;
#0 i_fu_146 = 5'd0;
#0 ap_done_reg = 1'b0;
end

ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_main5_class_output_kernel_ROM_bkb #(
    .DataWidth( 14 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
main5_class_output_kernel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(main5_class_output_kernel_address0),
    .ce0(main5_class_output_kernel_ce0_local),
    .q0(main5_class_output_kernel_q0)
);

(* dissolve_hierarchy = "yes" *) ecg_fpga_top_sparsemux_49_5_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 15 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 15 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 15 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 15 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 15 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 15 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 15 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 15 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 15 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 15 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 15 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 15 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 15 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 15 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 15 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 15 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 15 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 15 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 15 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 15 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 15 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 15 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 15 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 15 ),
    .def_WIDTH( 15 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
sparsemux_49_5_15_1_1_U163(
    .din0(in_q12_0_val),
    .din1(in_q12_1_val),
    .din2(in_q12_2_val),
    .din3(in_q12_3_val),
    .din4(in_q12_4_val),
    .din5(in_q12_5_val),
    .din6(in_q12_6_val),
    .din7(in_q12_7_val),
    .din8(in_q12_8_val),
    .din9(in_q12_9_val),
    .din10(in_q12_10_val),
    .din11(in_q12_11_val),
    .din12(in_q12_12_val),
    .din13(in_q12_13_val),
    .din14(in_q12_14_val),
    .din15(in_q12_15_val),
    .din16(in_q12_16_val),
    .din17(in_q12_17_val),
    .din18(in_q12_18_val),
    .din19(in_q12_19_val),
    .din20(in_q12_20_val),
    .din21(in_q12_21_val),
    .din22(in_q12_22_val),
    .din23(in_q12_23_val),
    .def(tmp_cast_fu_359_p49),
    .sel(ap_sig_allocacmp_i_4),
    .dout(tmp_cast_fu_359_p51)
);

ecg_fpga_top_mac_muladd_15ns_14s_33s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 33 ))
mac_muladd_15ns_14s_33s_33_4_1_U164(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_512_p0),
    .din1(main5_class_output_kernel_q0),
    .din2(ap_sig_allocacmp_acc_load_2),
    .ce(1'b1),
    .dout(grp_fu_512_p3)
);

ecg_fpga_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_142 <= sext_ln82_cast_fu_330_p1;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_fu_142 <= grp_fu_512_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln84_fu_347_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_146 <= add_ln84_fu_353_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_146 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_4_reg_541 <= ap_sig_allocacmp_i_4;
        icmp_ln84_reg_547 <= icmp_ln84_fu_347_p2;
        icmp_ln84_reg_547_pp0_iter1_reg <= icmp_ln84_reg_547;
        tmp_cast_reg_551 <= tmp_cast_fu_359_p51;
        tmp_cast_reg_551_pp0_iter1_reg <= tmp_cast_reg_551;
        zext_ln81_1_cast_reg_536[2 : 0] <= zext_ln81_1_cast_fu_326_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln84_reg_547_pp0_iter2_reg <= icmp_ln84_reg_547_pp0_iter1_reg;
        icmp_ln84_reg_547_pp0_iter3_reg <= icmp_ln84_reg_547_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln84_reg_547_pp0_iter3_reg == 1'd1))) begin
        acc_2_out_ap_vld = 1'b1;
    end else begin
        acc_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln84_fu_347_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_acc_load_2 = grp_fu_512_p3;
    end else begin
        ap_sig_allocacmp_acc_load_2 = acc_fu_142;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        main5_class_output_kernel_ce0_local = 1'b1;
    end else begin
        main5_class_output_kernel_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_2_out = acc_fu_142;

assign add_ln84_fu_353_p2 = (ap_sig_allocacmp_i_4 + 5'd1);

assign add_ln86_1_fu_478_p2 = (p_shl_fu_471_p3 + zext_ln86_fu_468_p1);

assign add_ln86_fu_484_p2 = (add_ln86_1_fu_478_p2 + zext_ln81_1_cast_reg_536);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_512_p0 = grp_fu_512_p00;

assign grp_fu_512_p00 = tmp_cast_reg_551_pp0_iter1_reg;

assign icmp_ln84_fu_347_p2 = ((ap_sig_allocacmp_i_4 == 5'd24) ? 1'b1 : 1'b0);

assign main5_class_output_kernel_address0 = zext_ln87_fu_489_p1;

assign p_shl_fu_471_p3 = {{i_4_reg_541}, {2'd0}};

assign sext_ln82_cast_fu_330_p1 = $signed(sext_ln82);

assign tmp_cast_fu_359_p49 = 'bx;

assign zext_ln81_1_cast_fu_326_p1 = zext_ln81_1;

assign zext_ln86_fu_468_p1 = i_4_reg_541;

assign zext_ln87_fu_489_p1 = add_ln86_fu_484_p2;

always @ (posedge ap_clk) begin
    zext_ln81_1_cast_reg_536[6:3] <= 4'b0000;
end

endmodule //ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2
