// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln58,
        in_q12_0_val,
        in_q12_1_val,
        in_q12_2_val,
        in_q12_3_val,
        in_q12_4_val,
        in_q12_5_val,
        in_q12_6_val,
        in_q12_7_val,
        in_q12_8_val,
        in_q12_9_val,
        in_q12_10_val,
        in_q12_11_val,
        in_q12_12_val,
        in_q12_13_val,
        in_q12_14_val,
        in_q12_15_val,
        in_q12_16_val,
        in_q12_17_val,
        in_q12_18_val,
        in_q12_19_val,
        in_q12_20_val,
        in_q12_21_val,
        in_q12_22_val,
        in_q12_23_val,
        in_q12_24_val,
        in_q12_25_val,
        in_q12_26_val,
        in_q12_27_val,
        in_q12_28_val,
        in_q12_29_val,
        in_q12_30_val,
        in_q12_31_val,
        in_q12_32_val,
        in_q12_33_val,
        in_q12_34_val,
        in_q12_35_val,
        in_q12_36_val,
        in_q12_37_val,
        in_q12_38_val,
        in_q12_39_val,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] zext_ln58;
input  [15:0] in_q12_0_val;
input  [15:0] in_q12_1_val;
input  [15:0] in_q12_2_val;
input  [15:0] in_q12_3_val;
input  [15:0] in_q12_4_val;
input  [15:0] in_q12_5_val;
input  [15:0] in_q12_6_val;
input  [15:0] in_q12_7_val;
input  [15:0] in_q12_8_val;
input  [15:0] in_q12_9_val;
input  [15:0] in_q12_10_val;
input  [15:0] in_q12_11_val;
input  [15:0] in_q12_12_val;
input  [15:0] in_q12_13_val;
input  [15:0] in_q12_14_val;
input  [15:0] in_q12_15_val;
input  [15:0] in_q12_16_val;
input  [15:0] in_q12_17_val;
input  [15:0] in_q12_18_val;
input  [15:0] in_q12_19_val;
input  [15:0] in_q12_20_val;
input  [15:0] in_q12_21_val;
input  [15:0] in_q12_22_val;
input  [15:0] in_q12_23_val;
input  [15:0] in_q12_24_val;
input  [15:0] in_q12_25_val;
input  [15:0] in_q12_26_val;
input  [15:0] in_q12_27_val;
input  [15:0] in_q12_28_val;
input  [15:0] in_q12_29_val;
input  [15:0] in_q12_30_val;
input  [15:0] in_q12_31_val;
input  [15:0] in_q12_32_val;
input  [15:0] in_q12_33_val;
input  [15:0] in_q12_34_val;
input  [15:0] in_q12_35_val;
input  [15:0] in_q12_36_val;
input  [15:0] in_q12_37_val;
input  [15:0] in_q12_38_val;
input  [15:0] in_q12_39_val;
output  [32:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln61_fu_499_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] main5_dense_kernel_address0;
wire  signed [11:0] main5_dense_kernel_q0;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] zext_ln58_cast_fu_482_p1;
reg   [9:0] zext_ln58_cast_reg_764;
reg   [5:0] i_3_reg_769;
reg   [0:0] icmp_ln61_reg_775;
reg   [0:0] icmp_ln61_reg_775_pp0_iter1_reg;
reg   [0:0] icmp_ln61_reg_775_pp0_iter2_reg;
reg   [0:0] icmp_ln61_reg_775_pp0_iter3_reg;
wire   [15:0] tmp_fu_511_p83;
reg   [15:0] tmp_reg_779;
reg  signed [15:0] tmp_reg_779_pp0_iter1_reg;
wire   [63:0] zext_ln64_fu_717_p1;
wire    ap_block_pp0_stage0;
reg   [32:0] acc_fu_208;
wire  signed [32:0] grp_fu_740_p3;
reg  signed [32:0] ap_sig_allocacmp_acc_load;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [5:0] i_fu_212;
wire   [5:0] add_ln61_fu_505_p2;
reg   [5:0] ap_sig_allocacmp_i_3;
wire    ap_block_pp0_stage0_01001;
reg    main5_dense_kernel_ce0_local;
wire   [15:0] tmp_fu_511_p81;
wire   [4:0] trunc_ln63_fu_684_p1;
wire   [8:0] tmp_3_fu_695_p3;
wire   [9:0] p_shl_fu_687_p3;
wire   [9:0] zext_ln63_fu_702_p1;
wire   [9:0] sub_ln63_fu_706_p2;
wire   [9:0] add_ln63_fu_712_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] tmp_fu_511_p1;
wire   [5:0] tmp_fu_511_p3;
wire   [5:0] tmp_fu_511_p5;
wire   [5:0] tmp_fu_511_p7;
wire   [5:0] tmp_fu_511_p9;
wire   [5:0] tmp_fu_511_p11;
wire   [5:0] tmp_fu_511_p13;
wire   [5:0] tmp_fu_511_p15;
wire   [5:0] tmp_fu_511_p17;
wire   [5:0] tmp_fu_511_p19;
wire   [5:0] tmp_fu_511_p21;
wire   [5:0] tmp_fu_511_p23;
wire   [5:0] tmp_fu_511_p25;
wire   [5:0] tmp_fu_511_p27;
wire   [5:0] tmp_fu_511_p29;
wire   [5:0] tmp_fu_511_p31;
wire   [5:0] tmp_fu_511_p33;
wire   [5:0] tmp_fu_511_p35;
wire   [5:0] tmp_fu_511_p37;
wire   [5:0] tmp_fu_511_p39;
wire   [5:0] tmp_fu_511_p41;
wire   [5:0] tmp_fu_511_p43;
wire   [5:0] tmp_fu_511_p45;
wire   [5:0] tmp_fu_511_p47;
wire   [5:0] tmp_fu_511_p49;
wire   [5:0] tmp_fu_511_p51;
wire   [5:0] tmp_fu_511_p53;
wire   [5:0] tmp_fu_511_p55;
wire   [5:0] tmp_fu_511_p57;
wire   [5:0] tmp_fu_511_p59;
wire   [5:0] tmp_fu_511_p61;
wire   [5:0] tmp_fu_511_p63;
wire  signed [5:0] tmp_fu_511_p65;
wire  signed [5:0] tmp_fu_511_p67;
wire  signed [5:0] tmp_fu_511_p69;
wire  signed [5:0] tmp_fu_511_p71;
wire  signed [5:0] tmp_fu_511_p73;
wire  signed [5:0] tmp_fu_511_p75;
wire  signed [5:0] tmp_fu_511_p77;
wire  signed [5:0] tmp_fu_511_p79;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 acc_fu_208 = 33'd0;
#0 i_fu_212 = 6'd0;
#0 ap_done_reg = 1'b0;
end

ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_main5_dense_kernel_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
main5_dense_kernel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(main5_dense_kernel_address0),
    .ce0(main5_dense_kernel_ce0_local),
    .q0(main5_dense_kernel_q0)
);

(* dissolve_hierarchy = "yes" *) ecg_fpga_top_sparsemux_81_6_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 16 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 16 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 16 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 16 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 16 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 16 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 16 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 16 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
sparsemux_81_6_16_1_1_U52(
    .din0(in_q12_0_val),
    .din1(in_q12_1_val),
    .din2(in_q12_2_val),
    .din3(in_q12_3_val),
    .din4(in_q12_4_val),
    .din5(in_q12_5_val),
    .din6(in_q12_6_val),
    .din7(in_q12_7_val),
    .din8(in_q12_8_val),
    .din9(in_q12_9_val),
    .din10(in_q12_10_val),
    .din11(in_q12_11_val),
    .din12(in_q12_12_val),
    .din13(in_q12_13_val),
    .din14(in_q12_14_val),
    .din15(in_q12_15_val),
    .din16(in_q12_16_val),
    .din17(in_q12_17_val),
    .din18(in_q12_18_val),
    .din19(in_q12_19_val),
    .din20(in_q12_20_val),
    .din21(in_q12_21_val),
    .din22(in_q12_22_val),
    .din23(in_q12_23_val),
    .din24(in_q12_24_val),
    .din25(in_q12_25_val),
    .din26(in_q12_26_val),
    .din27(in_q12_27_val),
    .din28(in_q12_28_val),
    .din29(in_q12_29_val),
    .din30(in_q12_30_val),
    .din31(in_q12_31_val),
    .din32(in_q12_32_val),
    .din33(in_q12_33_val),
    .din34(in_q12_34_val),
    .din35(in_q12_35_val),
    .din36(in_q12_36_val),
    .din37(in_q12_37_val),
    .din38(in_q12_38_val),
    .din39(in_q12_39_val),
    .def(tmp_fu_511_p81),
    .sel(ap_sig_allocacmp_i_3),
    .dout(tmp_fu_511_p83)
);

ecg_fpga_top_mac_muladd_16s_12s_33s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 33 ))
mac_muladd_16s_12s_33s_33_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_779_pp0_iter1_reg),
    .din1(main5_dense_kernel_q0),
    .din2(ap_sig_allocacmp_acc_load),
    .ce(1'b1),
    .dout(grp_fu_740_p3)
);

ecg_fpga_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_208 <= 33'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_fu_208 <= grp_fu_740_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_499_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_212 <= add_ln61_fu_505_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_212 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_3_reg_769 <= ap_sig_allocacmp_i_3;
        icmp_ln61_reg_775 <= icmp_ln61_fu_499_p2;
        icmp_ln61_reg_775_pp0_iter1_reg <= icmp_ln61_reg_775;
        tmp_reg_779 <= tmp_fu_511_p83;
        tmp_reg_779_pp0_iter1_reg <= tmp_reg_779;
        zext_ln58_cast_reg_764[4 : 0] <= zext_ln58_cast_fu_482_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln61_reg_775_pp0_iter2_reg <= icmp_ln61_reg_775_pp0_iter1_reg;
        icmp_ln61_reg_775_pp0_iter3_reg <= icmp_ln61_reg_775_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln61_reg_775_pp0_iter3_reg == 1'd1))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln61_fu_499_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_acc_load = grp_fu_740_p3;
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_208;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_212;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        main5_dense_kernel_ce0_local = 1'b1;
    end else begin
        main5_dense_kernel_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_out = acc_fu_208;

assign add_ln61_fu_505_p2 = (ap_sig_allocacmp_i_3 + 6'd1);

assign add_ln63_fu_712_p2 = (sub_ln63_fu_706_p2 + zext_ln58_cast_reg_764);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln61_fu_499_p2 = ((ap_sig_allocacmp_i_3 == 6'd40) ? 1'b1 : 1'b0);

assign main5_dense_kernel_address0 = zext_ln64_fu_717_p1;

assign p_shl_fu_687_p3 = {{trunc_ln63_fu_684_p1}, {5'd0}};

assign sub_ln63_fu_706_p2 = (p_shl_fu_687_p3 - zext_ln63_fu_702_p1);

assign tmp_3_fu_695_p3 = {{i_3_reg_769}, {3'd0}};

assign tmp_fu_511_p81 = 'bx;

assign trunc_ln63_fu_684_p1 = i_3_reg_769[4:0];

assign zext_ln58_cast_fu_482_p1 = zext_ln58;

assign zext_ln63_fu_702_p1 = tmp_3_fu_695_p3;

assign zext_ln64_fu_717_p1 = add_ln63_fu_712_p2;

always @ (posedge ap_clk) begin
    zext_ln58_cast_reg_764[9:5] <= 5'b00000;
end

endmodule //ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2
