// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_dense_40x24_relu_int (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_q12_0_val,
        in_q12_1_val,
        in_q12_2_val,
        in_q12_3_val,
        in_q12_4_val,
        in_q12_5_val,
        in_q12_6_val,
        in_q12_7_val,
        in_q12_8_val,
        in_q12_9_val,
        in_q12_10_val,
        in_q12_11_val,
        in_q12_12_val,
        in_q12_13_val,
        in_q12_14_val,
        in_q12_15_val,
        in_q12_16_val,
        in_q12_17_val,
        in_q12_18_val,
        in_q12_19_val,
        in_q12_20_val,
        in_q12_21_val,
        in_q12_22_val,
        in_q12_23_val,
        in_q12_24_val,
        in_q12_25_val,
        in_q12_26_val,
        in_q12_27_val,
        in_q12_28_val,
        in_q12_29_val,
        in_q12_30_val,
        in_q12_31_val,
        in_q12_32_val,
        in_q12_33_val,
        in_q12_34_val,
        in_q12_35_val,
        in_q12_36_val,
        in_q12_37_val,
        in_q12_38_val,
        in_q12_39_val,
        out_q12_0,
        out_q12_0_ap_vld,
        out_q12_1,
        out_q12_1_ap_vld,
        out_q12_2,
        out_q12_2_ap_vld,
        out_q12_3,
        out_q12_3_ap_vld,
        out_q12_4,
        out_q12_4_ap_vld,
        out_q12_5,
        out_q12_5_ap_vld,
        out_q12_6,
        out_q12_6_ap_vld,
        out_q12_7,
        out_q12_7_ap_vld,
        out_q12_8,
        out_q12_8_ap_vld,
        out_q12_9,
        out_q12_9_ap_vld,
        out_q12_10,
        out_q12_10_ap_vld,
        out_q12_11,
        out_q12_11_ap_vld,
        out_q12_12,
        out_q12_12_ap_vld,
        out_q12_13,
        out_q12_13_ap_vld,
        out_q12_14,
        out_q12_14_ap_vld,
        out_q12_15,
        out_q12_15_ap_vld,
        out_q12_16,
        out_q12_16_ap_vld,
        out_q12_17,
        out_q12_17_ap_vld,
        out_q12_18,
        out_q12_18_ap_vld,
        out_q12_19,
        out_q12_19_ap_vld,
        out_q12_20,
        out_q12_20_ap_vld,
        out_q12_21,
        out_q12_21_ap_vld,
        out_q12_22,
        out_q12_22_ap_vld,
        out_q12_23,
        out_q12_23_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] in_q12_0_val;
input  [15:0] in_q12_1_val;
input  [15:0] in_q12_2_val;
input  [15:0] in_q12_3_val;
input  [15:0] in_q12_4_val;
input  [15:0] in_q12_5_val;
input  [15:0] in_q12_6_val;
input  [15:0] in_q12_7_val;
input  [15:0] in_q12_8_val;
input  [15:0] in_q12_9_val;
input  [15:0] in_q12_10_val;
input  [15:0] in_q12_11_val;
input  [15:0] in_q12_12_val;
input  [15:0] in_q12_13_val;
input  [15:0] in_q12_14_val;
input  [15:0] in_q12_15_val;
input  [15:0] in_q12_16_val;
input  [15:0] in_q12_17_val;
input  [15:0] in_q12_18_val;
input  [15:0] in_q12_19_val;
input  [15:0] in_q12_20_val;
input  [15:0] in_q12_21_val;
input  [15:0] in_q12_22_val;
input  [15:0] in_q12_23_val;
input  [15:0] in_q12_24_val;
input  [15:0] in_q12_25_val;
input  [15:0] in_q12_26_val;
input  [15:0] in_q12_27_val;
input  [15:0] in_q12_28_val;
input  [15:0] in_q12_29_val;
input  [15:0] in_q12_30_val;
input  [15:0] in_q12_31_val;
input  [15:0] in_q12_32_val;
input  [15:0] in_q12_33_val;
input  [15:0] in_q12_34_val;
input  [15:0] in_q12_35_val;
input  [15:0] in_q12_36_val;
input  [15:0] in_q12_37_val;
input  [15:0] in_q12_38_val;
input  [15:0] in_q12_39_val;
output  [14:0] out_q12_0;
output   out_q12_0_ap_vld;
output  [14:0] out_q12_1;
output   out_q12_1_ap_vld;
output  [14:0] out_q12_2;
output   out_q12_2_ap_vld;
output  [14:0] out_q12_3;
output   out_q12_3_ap_vld;
output  [14:0] out_q12_4;
output   out_q12_4_ap_vld;
output  [14:0] out_q12_5;
output   out_q12_5_ap_vld;
output  [14:0] out_q12_6;
output   out_q12_6_ap_vld;
output  [14:0] out_q12_7;
output   out_q12_7_ap_vld;
output  [14:0] out_q12_8;
output   out_q12_8_ap_vld;
output  [14:0] out_q12_9;
output   out_q12_9_ap_vld;
output  [14:0] out_q12_10;
output   out_q12_10_ap_vld;
output  [14:0] out_q12_11;
output   out_q12_11_ap_vld;
output  [14:0] out_q12_12;
output   out_q12_12_ap_vld;
output  [14:0] out_q12_13;
output   out_q12_13_ap_vld;
output  [14:0] out_q12_14;
output   out_q12_14_ap_vld;
output  [14:0] out_q12_15;
output   out_q12_15_ap_vld;
output  [14:0] out_q12_16;
output   out_q12_16_ap_vld;
output  [14:0] out_q12_17;
output   out_q12_17_ap_vld;
output  [14:0] out_q12_18;
output   out_q12_18_ap_vld;
output  [14:0] out_q12_19;
output   out_q12_19_ap_vld;
output  [14:0] out_q12_20;
output   out_q12_20_ap_vld;
output  [14:0] out_q12_21;
output   out_q12_21_ap_vld;
output  [14:0] out_q12_22;
output   out_q12_22_ap_vld;
output  [14:0] out_q12_23;
output   out_q12_23_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_q12_0_ap_vld;
reg out_q12_1_ap_vld;
reg out_q12_2_ap_vld;
reg out_q12_3_ap_vld;
reg out_q12_4_ap_vld;
reg out_q12_5_ap_vld;
reg out_q12_6_ap_vld;
reg out_q12_7_ap_vld;
reg out_q12_8_ap_vld;
reg out_q12_9_ap_vld;
reg out_q12_10_ap_vld;
reg out_q12_11_ap_vld;
reg out_q12_12_ap_vld;
reg out_q12_13_ap_vld;
reg out_q12_14_ap_vld;
reg out_q12_15_ap_vld;
reg out_q12_16_ap_vld;
reg out_q12_17_ap_vld;
reg out_q12_18_ap_vld;
reg out_q12_19_ap_vld;
reg out_q12_20_ap_vld;
reg out_q12_21_ap_vld;
reg out_q12_22_ap_vld;
reg out_q12_23_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] o_1_reg_1080;
wire    ap_CS_fsm_state2;
wire   [4:0] add_ln58_fu_699_p2;
reg   [4:0] add_ln58_reg_1087;
wire    grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start;
wire    grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_done;
wire    grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_idle;
wire    grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_ready;
wire   [32:0] grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out;
wire    grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out_ap_vld;
reg    grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start_reg;
wire   [0:0] icmp_ln58_fu_693_p2;
wire    ap_CS_fsm_state3;
reg   [4:0] o_fu_220;
wire    ap_CS_fsm_state4;
wire   [14:0] select_ln14_fu_782_p3;
reg    ap_predicate_pred278_state4;
reg    ap_predicate_pred286_state4;
reg    ap_predicate_pred291_state4;
reg    ap_predicate_pred296_state4;
reg    ap_predicate_pred301_state4;
reg    ap_predicate_pred306_state4;
reg    ap_predicate_pred311_state4;
reg    ap_predicate_pred316_state4;
reg    ap_predicate_pred321_state4;
reg    ap_predicate_pred326_state4;
reg    ap_predicate_pred331_state4;
reg    ap_predicate_pred336_state4;
reg    ap_predicate_pred341_state4;
reg    ap_predicate_pred346_state4;
reg    ap_predicate_pred351_state4;
reg    ap_predicate_pred356_state4;
reg    ap_predicate_pred361_state4;
reg    ap_predicate_pred366_state4;
reg    ap_predicate_pred371_state4;
reg    ap_predicate_pred376_state4;
reg    ap_predicate_pred381_state4;
reg    ap_predicate_pred386_state4;
reg    ap_predicate_pred390_state4;
reg    ap_predicate_pred438_state4;
wire   [5:0] tmp_fu_718_p4;
wire   [20:0] trunc_ln_fu_708_p4;
wire   [0:0] icmp_ln6_fu_728_p2;
wire   [0:0] icmp_ln7_fu_734_p2;
wire   [0:0] or_ln6_fu_758_p2;
wire   [15:0] select_ln6_fu_750_p3;
wire   [15:0] trunc_ln8_fu_740_p4;
wire   [15:0] select_ln6_2_fu_764_p3;
wire   [0:0] icmp_ln14_fu_776_p2;
wire   [14:0] trunc_ln11_fu_772_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start_reg = 1'b0;
#0 o_fu_220 = 5'd0;
end

ecg_fpga_top_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2 grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start),
    .ap_done(grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_done),
    .ap_idle(grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_idle),
    .ap_ready(grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_ready),
    .zext_ln58(o_fu_220),
    .in_q12_0_val(in_q12_0_val),
    .in_q12_1_val(in_q12_1_val),
    .in_q12_2_val(in_q12_2_val),
    .in_q12_3_val(in_q12_3_val),
    .in_q12_4_val(in_q12_4_val),
    .in_q12_5_val(in_q12_5_val),
    .in_q12_6_val(in_q12_6_val),
    .in_q12_7_val(in_q12_7_val),
    .in_q12_8_val(in_q12_8_val),
    .in_q12_9_val(in_q12_9_val),
    .in_q12_10_val(in_q12_10_val),
    .in_q12_11_val(in_q12_11_val),
    .in_q12_12_val(in_q12_12_val),
    .in_q12_13_val(in_q12_13_val),
    .in_q12_14_val(in_q12_14_val),
    .in_q12_15_val(in_q12_15_val),
    .in_q12_16_val(in_q12_16_val),
    .in_q12_17_val(in_q12_17_val),
    .in_q12_18_val(in_q12_18_val),
    .in_q12_19_val(in_q12_19_val),
    .in_q12_20_val(in_q12_20_val),
    .in_q12_21_val(in_q12_21_val),
    .in_q12_22_val(in_q12_22_val),
    .in_q12_23_val(in_q12_23_val),
    .in_q12_24_val(in_q12_24_val),
    .in_q12_25_val(in_q12_25_val),
    .in_q12_26_val(in_q12_26_val),
    .in_q12_27_val(in_q12_27_val),
    .in_q12_28_val(in_q12_28_val),
    .in_q12_29_val(in_q12_29_val),
    .in_q12_30_val(in_q12_30_val),
    .in_q12_31_val(in_q12_31_val),
    .in_q12_32_val(in_q12_32_val),
    .in_q12_33_val(in_q12_33_val),
    .in_q12_34_val(in_q12_34_val),
    .in_q12_35_val(in_q12_35_val),
    .in_q12_36_val(in_q12_36_val),
    .in_q12_37_val(in_q12_37_val),
    .in_q12_38_val(in_q12_38_val),
    .in_q12_39_val(in_q12_39_val),
    .acc_out(grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out),
    .acc_out_ap_vld(grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln58_fu_693_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start_reg <= 1'b1;
        end else if ((grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_ready == 1'b1)) begin
            grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        o_fu_220 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        o_fu_220 <= add_ln58_reg_1087;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln58_reg_1087 <= add_ln58_fu_699_p2;
        o_1_reg_1080 <= o_fu_220;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_predicate_pred278_state4 <= (o_1_reg_1080 == 5'd22);
        ap_predicate_pred286_state4 <= (o_1_reg_1080 == 5'd21);
        ap_predicate_pred291_state4 <= (o_1_reg_1080 == 5'd20);
        ap_predicate_pred296_state4 <= (o_1_reg_1080 == 5'd19);
        ap_predicate_pred301_state4 <= (o_1_reg_1080 == 5'd18);
        ap_predicate_pred306_state4 <= (o_1_reg_1080 == 5'd17);
        ap_predicate_pred311_state4 <= (o_1_reg_1080 == 5'd16);
        ap_predicate_pred316_state4 <= (o_1_reg_1080 == 5'd15);
        ap_predicate_pred321_state4 <= (o_1_reg_1080 == 5'd14);
        ap_predicate_pred326_state4 <= (o_1_reg_1080 == 5'd13);
        ap_predicate_pred331_state4 <= (o_1_reg_1080 == 5'd12);
        ap_predicate_pred336_state4 <= (o_1_reg_1080 == 5'd11);
        ap_predicate_pred341_state4 <= (o_1_reg_1080 == 5'd10);
        ap_predicate_pred346_state4 <= (o_1_reg_1080 == 5'd9);
        ap_predicate_pred351_state4 <= (o_1_reg_1080 == 5'd8);
        ap_predicate_pred356_state4 <= (o_1_reg_1080 == 5'd7);
        ap_predicate_pred361_state4 <= (o_1_reg_1080 == 5'd6);
        ap_predicate_pred366_state4 <= (o_1_reg_1080 == 5'd5);
        ap_predicate_pred371_state4 <= (o_1_reg_1080 == 5'd4);
        ap_predicate_pred376_state4 <= (o_1_reg_1080 == 5'd3);
        ap_predicate_pred381_state4 <= (o_1_reg_1080 == 5'd2);
        ap_predicate_pred386_state4 <= (o_1_reg_1080 == 5'd1);
        ap_predicate_pred390_state4 <= (o_1_reg_1080 == 5'd0);
        ap_predicate_pred438_state4 <= (~(o_1_reg_1080 == 5'd0) & ~(o_1_reg_1080 == 5'd1) & ~(o_1_reg_1080 == 5'd2) & ~(o_1_reg_1080 == 5'd3) & ~(o_1_reg_1080 == 5'd4) & ~(o_1_reg_1080 == 5'd5) & ~(o_1_reg_1080 == 5'd6) & ~(o_1_reg_1080 == 5'd7) & ~(o_1_reg_1080 == 5'd8) & ~(o_1_reg_1080 == 5'd9) & ~(o_1_reg_1080 == 5'd10) & ~(o_1_reg_1080 == 5'd11) & ~(o_1_reg_1080 == 5'd12) & ~(o_1_reg_1080 == 5'd13) & ~(o_1_reg_1080 == 5'd14) & ~(o_1_reg_1080 == 5'd15) & ~(o_1_reg_1080 == 5'd16) & ~(o_1_reg_1080 == 5'd17) & ~(o_1_reg_1080 == 5'd18) & ~(o_1_reg_1080 == 5'd19) & ~(o_1_reg_1080 == 5'd20) & ~(o_1_reg_1080 == 5'd21) & ~(o_1_reg_1080 == 5'd22));
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln58_fu_693_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln58_fu_693_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred390_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_0_ap_vld = 1'b1;
    end else begin
        out_q12_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred341_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_10_ap_vld = 1'b1;
    end else begin
        out_q12_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred336_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_11_ap_vld = 1'b1;
    end else begin
        out_q12_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred331_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_12_ap_vld = 1'b1;
    end else begin
        out_q12_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred326_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_13_ap_vld = 1'b1;
    end else begin
        out_q12_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred321_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_14_ap_vld = 1'b1;
    end else begin
        out_q12_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred316_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_15_ap_vld = 1'b1;
    end else begin
        out_q12_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred311_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_16_ap_vld = 1'b1;
    end else begin
        out_q12_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred306_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_17_ap_vld = 1'b1;
    end else begin
        out_q12_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred301_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_18_ap_vld = 1'b1;
    end else begin
        out_q12_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred296_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_19_ap_vld = 1'b1;
    end else begin
        out_q12_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred386_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_1_ap_vld = 1'b1;
    end else begin
        out_q12_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred291_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_20_ap_vld = 1'b1;
    end else begin
        out_q12_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred286_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_21_ap_vld = 1'b1;
    end else begin
        out_q12_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred278_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_22_ap_vld = 1'b1;
    end else begin
        out_q12_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred438_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_23_ap_vld = 1'b1;
    end else begin
        out_q12_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred381_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_2_ap_vld = 1'b1;
    end else begin
        out_q12_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred376_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_3_ap_vld = 1'b1;
    end else begin
        out_q12_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred371_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_4_ap_vld = 1'b1;
    end else begin
        out_q12_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred366_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_5_ap_vld = 1'b1;
    end else begin
        out_q12_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred361_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_6_ap_vld = 1'b1;
    end else begin
        out_q12_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred356_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_7_ap_vld = 1'b1;
    end else begin
        out_q12_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred351_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_8_ap_vld = 1'b1;
    end else begin
        out_q12_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred346_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_q12_9_ap_vld = 1'b1;
    end else begin
        out_q12_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln58_fu_693_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_fu_699_p2 = (o_fu_220 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start = grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_ap_start_reg;

assign icmp_ln14_fu_776_p2 = (($signed(select_ln6_2_fu_764_p3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_693_p2 = ((o_fu_220 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_728_p2 = (($signed(tmp_fu_718_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_734_p2 = (($signed(trunc_ln_fu_708_p4) < $signed(21'd2064384)) ? 1'b1 : 1'b0);

assign or_ln6_fu_758_p2 = (icmp_ln7_fu_734_p2 | icmp_ln6_fu_728_p2);

assign out_q12_0 = select_ln14_fu_782_p3;

assign out_q12_1 = select_ln14_fu_782_p3;

assign out_q12_10 = select_ln14_fu_782_p3;

assign out_q12_11 = select_ln14_fu_782_p3;

assign out_q12_12 = select_ln14_fu_782_p3;

assign out_q12_13 = select_ln14_fu_782_p3;

assign out_q12_14 = select_ln14_fu_782_p3;

assign out_q12_15 = select_ln14_fu_782_p3;

assign out_q12_16 = select_ln14_fu_782_p3;

assign out_q12_17 = select_ln14_fu_782_p3;

assign out_q12_18 = select_ln14_fu_782_p3;

assign out_q12_19 = select_ln14_fu_782_p3;

assign out_q12_2 = select_ln14_fu_782_p3;

assign out_q12_20 = select_ln14_fu_782_p3;

assign out_q12_21 = select_ln14_fu_782_p3;

assign out_q12_22 = select_ln14_fu_782_p3;

assign out_q12_23 = select_ln14_fu_782_p3;

assign out_q12_3 = select_ln14_fu_782_p3;

assign out_q12_4 = select_ln14_fu_782_p3;

assign out_q12_5 = select_ln14_fu_782_p3;

assign out_q12_6 = select_ln14_fu_782_p3;

assign out_q12_7 = select_ln14_fu_782_p3;

assign out_q12_8 = select_ln14_fu_782_p3;

assign out_q12_9 = select_ln14_fu_782_p3;

assign select_ln14_fu_782_p3 = ((icmp_ln14_fu_776_p2[0:0] == 1'b1) ? trunc_ln11_fu_772_p1 : 15'd0);

assign select_ln6_2_fu_764_p3 = ((or_ln6_fu_758_p2[0:0] == 1'b1) ? select_ln6_fu_750_p3 : trunc_ln8_fu_740_p4);

assign select_ln6_fu_750_p3 = ((icmp_ln6_fu_728_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign tmp_fu_718_p4 = {{grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out[32:27]}};

assign trunc_ln11_fu_772_p1 = select_ln6_2_fu_764_p3[14:0];

assign trunc_ln8_fu_740_p4 = {{grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out[27:12]}};

assign trunc_ln_fu_708_p4 = {{grp_dense_40x24_relu_int_Pipeline_VITIS_LOOP_61_2_fu_636_acc_out[32:12]}};

endmodule //ecg_fpga_top_dense_40x24_relu_int
