// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_extract_light_features_40_int (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        beat_in_q12_address0,
        beat_in_q12_ce0,
        beat_in_q12_q0,
        feat_q12_0,
        feat_q12_0_ap_vld,
        feat_q12_1,
        feat_q12_1_ap_vld,
        feat_q12_2,
        feat_q12_2_ap_vld,
        feat_q12_3,
        feat_q12_3_ap_vld,
        feat_q12_4,
        feat_q12_4_ap_vld,
        feat_q12_5,
        feat_q12_5_ap_vld,
        feat_q12_6,
        feat_q12_6_ap_vld,
        feat_q12_7,
        feat_q12_7_ap_vld,
        feat_q12_8,
        feat_q12_8_ap_vld,
        feat_q12_9,
        feat_q12_9_ap_vld,
        feat_q12_10,
        feat_q12_10_ap_vld,
        feat_q12_11,
        feat_q12_11_ap_vld,
        feat_q12_12,
        feat_q12_12_ap_vld,
        feat_q12_13,
        feat_q12_13_ap_vld,
        feat_q12_14,
        feat_q12_14_ap_vld,
        feat_q12_15,
        feat_q12_15_ap_vld,
        feat_q12_16,
        feat_q12_16_ap_vld,
        feat_q12_17,
        feat_q12_17_ap_vld,
        feat_q12_18,
        feat_q12_18_ap_vld,
        feat_q12_19,
        feat_q12_19_ap_vld,
        feat_q12_20,
        feat_q12_20_ap_vld,
        feat_q12_21,
        feat_q12_21_ap_vld,
        feat_q12_22,
        feat_q12_22_ap_vld,
        feat_q12_23,
        feat_q12_23_ap_vld,
        feat_q12_24,
        feat_q12_24_ap_vld,
        feat_q12_25,
        feat_q12_25_ap_vld,
        feat_q12_26,
        feat_q12_26_ap_vld,
        feat_q12_27,
        feat_q12_27_ap_vld,
        feat_q12_28,
        feat_q12_28_ap_vld,
        feat_q12_29,
        feat_q12_29_ap_vld,
        feat_q12_30,
        feat_q12_30_ap_vld,
        feat_q12_31,
        feat_q12_31_ap_vld,
        feat_q12_32,
        feat_q12_32_ap_vld,
        feat_q12_33,
        feat_q12_33_ap_vld,
        feat_q12_34,
        feat_q12_34_ap_vld,
        feat_q12_35,
        feat_q12_35_ap_vld,
        feat_q12_36,
        feat_q12_36_ap_vld,
        feat_q12_37,
        feat_q12_37_ap_vld,
        feat_q12_38,
        feat_q12_38_ap_vld,
        feat_q12_39,
        feat_q12_39_ap_vld
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] beat_in_q12_address0;
output   beat_in_q12_ce0;
input  [15:0] beat_in_q12_q0;
output  [15:0] feat_q12_0;
output   feat_q12_0_ap_vld;
output  [15:0] feat_q12_1;
output   feat_q12_1_ap_vld;
output  [15:0] feat_q12_2;
output   feat_q12_2_ap_vld;
output  [15:0] feat_q12_3;
output   feat_q12_3_ap_vld;
output  [15:0] feat_q12_4;
output   feat_q12_4_ap_vld;
output  [15:0] feat_q12_5;
output   feat_q12_5_ap_vld;
output  [15:0] feat_q12_6;
output   feat_q12_6_ap_vld;
output  [15:0] feat_q12_7;
output   feat_q12_7_ap_vld;
output  [15:0] feat_q12_8;
output   feat_q12_8_ap_vld;
output  [15:0] feat_q12_9;
output   feat_q12_9_ap_vld;
output  [15:0] feat_q12_10;
output   feat_q12_10_ap_vld;
output  [15:0] feat_q12_11;
output   feat_q12_11_ap_vld;
output  [15:0] feat_q12_12;
output   feat_q12_12_ap_vld;
output  [15:0] feat_q12_13;
output   feat_q12_13_ap_vld;
output  [15:0] feat_q12_14;
output   feat_q12_14_ap_vld;
output  [15:0] feat_q12_15;
output   feat_q12_15_ap_vld;
output  [15:0] feat_q12_16;
output   feat_q12_16_ap_vld;
output  [15:0] feat_q12_17;
output   feat_q12_17_ap_vld;
output  [15:0] feat_q12_18;
output   feat_q12_18_ap_vld;
output  [15:0] feat_q12_19;
output   feat_q12_19_ap_vld;
output  [15:0] feat_q12_20;
output   feat_q12_20_ap_vld;
output  [15:0] feat_q12_21;
output   feat_q12_21_ap_vld;
output  [15:0] feat_q12_22;
output   feat_q12_22_ap_vld;
output  [15:0] feat_q12_23;
output   feat_q12_23_ap_vld;
output  [15:0] feat_q12_24;
output   feat_q12_24_ap_vld;
output  [15:0] feat_q12_25;
output   feat_q12_25_ap_vld;
output  [15:0] feat_q12_26;
output   feat_q12_26_ap_vld;
output  [15:0] feat_q12_27;
output   feat_q12_27_ap_vld;
output  [15:0] feat_q12_28;
output   feat_q12_28_ap_vld;
output  [15:0] feat_q12_29;
output   feat_q12_29_ap_vld;
output  [15:0] feat_q12_30;
output   feat_q12_30_ap_vld;
output  [15:0] feat_q12_31;
output   feat_q12_31_ap_vld;
output  [15:0] feat_q12_32;
output   feat_q12_32_ap_vld;
output  [15:0] feat_q12_33;
output   feat_q12_33_ap_vld;
output  [15:0] feat_q12_34;
output   feat_q12_34_ap_vld;
output  [15:0] feat_q12_35;
output   feat_q12_35_ap_vld;
output  [15:0] feat_q12_36;
output   feat_q12_36_ap_vld;
output  [15:0] feat_q12_37;
output   feat_q12_37_ap_vld;
output  [15:0] feat_q12_38;
output   feat_q12_38_ap_vld;
output  [15:0] feat_q12_39;
output   feat_q12_39_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] beat_in_q12_address0;
reg beat_in_q12_ce0;
reg feat_q12_0_ap_vld;
reg feat_q12_1_ap_vld;
reg feat_q12_2_ap_vld;
reg feat_q12_3_ap_vld;
reg feat_q12_4_ap_vld;
reg feat_q12_5_ap_vld;
reg feat_q12_6_ap_vld;
reg feat_q12_7_ap_vld;
reg feat_q12_8_ap_vld;
reg feat_q12_9_ap_vld;
reg feat_q12_10_ap_vld;
reg feat_q12_11_ap_vld;
reg feat_q12_12_ap_vld;
reg feat_q12_13_ap_vld;
reg feat_q12_14_ap_vld;
reg feat_q12_15_ap_vld;
reg feat_q12_16_ap_vld;
reg feat_q12_17_ap_vld;
reg feat_q12_18_ap_vld;
reg feat_q12_19_ap_vld;
reg feat_q12_20_ap_vld;
reg feat_q12_21_ap_vld;
reg feat_q12_22_ap_vld;
reg feat_q12_23_ap_vld;
reg feat_q12_24_ap_vld;
reg feat_q12_25_ap_vld;
reg feat_q12_26_ap_vld;
reg feat_q12_27_ap_vld;
reg feat_q12_28_ap_vld;
reg feat_q12_29_ap_vld;
reg feat_q12_30_ap_vld;
reg feat_q12_31_ap_vld;
reg feat_q12_32_ap_vld;
reg feat_q12_33_ap_vld;
reg feat_q12_34_ap_vld;
reg feat_q12_35_ap_vld;
reg feat_q12_36_ap_vld;
reg feat_q12_37_ap_vld;
reg feat_q12_38_ap_vld;
reg feat_q12_39_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] c_1_reg_776;
wire    ap_CS_fsm_state2;
wire   [4:0] add_ln24_fu_512_p2;
reg   [4:0] add_ln24_reg_783;
wire   [8:0] shl_ln_fu_518_p3;
reg   [8:0] shl_ln_reg_788;
reg   [15:0] prev_reg_798;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
reg   [0:0] tmp_2_reg_808;
wire   [0:0] icmp_ln6_fu_547_p2;
reg   [0:0] icmp_ln6_reg_814;
wire   [0:0] icmp_ln7_fu_553_p2;
reg   [0:0] icmp_ln7_reg_820;
wire   [64:0] grp_fu_493_p2;
reg   [64:0] mul_ln46_reg_825;
wire    ap_CS_fsm_state7;
reg   [15:0] tmp_1_cast_reg_830;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_idle;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_ready;
wire   [8:0] grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0;
wire   [19:0] grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out_ap_vld;
wire   [31:0] grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;
wire    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out_ap_vld;
reg    grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln27_fu_526_p1;
wire   [0:0] icmp_ln24_fu_506_p2;
reg   [4:0] c_fu_178;
wire    ap_CS_fsm_state8;
wire   [15:0] select_ln45_fu_612_p3;
reg    ap_predicate_pred215_state8;
wire   [15:0] select_ln6_1_fu_684_p3;
reg    ap_predicate_pred221_state8;
reg    ap_predicate_pred226_state8;
reg    ap_predicate_pred231_state8;
reg    ap_predicate_pred236_state8;
reg    ap_predicate_pred241_state8;
reg    ap_predicate_pred246_state8;
reg    ap_predicate_pred251_state8;
reg    ap_predicate_pred256_state8;
reg    ap_predicate_pred261_state8;
reg    ap_predicate_pred266_state8;
reg    ap_predicate_pred271_state8;
reg    ap_predicate_pred276_state8;
reg    ap_predicate_pred281_state8;
reg    ap_predicate_pred286_state8;
reg    ap_predicate_pred291_state8;
reg    ap_predicate_pred296_state8;
reg    ap_predicate_pred301_state8;
reg    ap_predicate_pred305_state8;
reg    ap_predicate_pred345_state8;
reg    beat_in_q12_ce0_local;
wire   [33:0] grp_fu_493_p1;
wire  signed [31:0] sext_ln46_fu_534_p0;
wire  signed [31:0] tmp_2_fu_539_p1;
wire  signed [31:0] icmp_ln6_fu_547_p0;
wire  signed [31:0] icmp_ln7_fu_553_p0;
wire   [19:0] sub_ln45_fu_580_p2;
wire   [15:0] trunc_ln45_1_fu_586_p4;
wire   [0:0] tmp_fu_572_p3;
wire   [15:0] sub_ln45_1_fu_596_p2;
wire   [15:0] trunc_ln45_2_fu_602_p4;
wire   [64:0] sub_ln46_fu_640_p2;
wire   [15:0] tmp_cast_fu_645_p4;
wire   [15:0] select_ln8_fu_655_p3;
wire   [15:0] sub_ln8_fu_661_p2;
wire   [0:0] or_ln6_fu_680_p2;
wire   [15:0] select_ln6_fu_673_p3;
wire   [15:0] select_ln46_fu_667_p3;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg = 1'b0;
#0 c_fu_178 = 5'd0;
end

ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2 grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start),
    .ap_done(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done),
    .ap_idle(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_idle),
    .ap_ready(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_ready),
    .prev(prev_reg_798),
    .shl_ln(shl_ln_reg_788),
    .beat_in_q12_address0(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0),
    .beat_in_q12_ce0(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0),
    .beat_in_q12_q0(beat_in_q12_q0),
    .sum_out(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out),
    .sum_out_ap_vld(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out_ap_vld),
    .diff_sum_out(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out),
    .diff_sum_out_ap_vld(grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out_ap_vld)
);

ecg_fpga_top_mul_32s_34ns_65_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln46_fu_534_p0),
    .din1(grp_fu_493_p1),
    .ce(1'b1),
    .dout(grp_fu_493_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg <= 1'b1;
        end else if ((grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_ready == 1'b1)) begin
            grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_fu_178 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        c_fu_178 <= add_ln24_reg_783;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln24_reg_783 <= add_ln24_fu_512_p2;
        c_1_reg_776 <= c_fu_178;
        shl_ln_reg_788[8 : 4] <= shl_ln_fu_518_p3[8 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_predicate_pred215_state8 <= (c_1_reg_776 == 5'd18);
        ap_predicate_pred221_state8 <= (c_1_reg_776 == 5'd17);
        ap_predicate_pred226_state8 <= (c_1_reg_776 == 5'd16);
        ap_predicate_pred231_state8 <= (c_1_reg_776 == 5'd15);
        ap_predicate_pred236_state8 <= (c_1_reg_776 == 5'd14);
        ap_predicate_pred241_state8 <= (c_1_reg_776 == 5'd13);
        ap_predicate_pred246_state8 <= (c_1_reg_776 == 5'd12);
        ap_predicate_pred251_state8 <= (c_1_reg_776 == 5'd11);
        ap_predicate_pred256_state8 <= (c_1_reg_776 == 5'd10);
        ap_predicate_pred261_state8 <= (c_1_reg_776 == 5'd9);
        ap_predicate_pred266_state8 <= (c_1_reg_776 == 5'd8);
        ap_predicate_pred271_state8 <= (c_1_reg_776 == 5'd7);
        ap_predicate_pred276_state8 <= (c_1_reg_776 == 5'd6);
        ap_predicate_pred281_state8 <= (c_1_reg_776 == 5'd5);
        ap_predicate_pred286_state8 <= (c_1_reg_776 == 5'd4);
        ap_predicate_pred291_state8 <= (c_1_reg_776 == 5'd3);
        ap_predicate_pred296_state8 <= (c_1_reg_776 == 5'd2);
        ap_predicate_pred301_state8 <= (c_1_reg_776 == 5'd1);
        ap_predicate_pred305_state8 <= (c_1_reg_776 == 5'd0);
        ap_predicate_pred345_state8 <= (~(c_1_reg_776 == 5'd0) & ~(c_1_reg_776 == 5'd1) & ~(c_1_reg_776 == 5'd2) & ~(c_1_reg_776 == 5'd3) & ~(c_1_reg_776 == 5'd4) & ~(c_1_reg_776 == 5'd5) & ~(c_1_reg_776 == 5'd6) & ~(c_1_reg_776 == 5'd7) & ~(c_1_reg_776 == 5'd8) & ~(c_1_reg_776 == 5'd9) & ~(c_1_reg_776 == 5'd10) & ~(c_1_reg_776 == 5'd11) & ~(c_1_reg_776 == 5'd12) & ~(c_1_reg_776 == 5'd13) & ~(c_1_reg_776 == 5'd14) & ~(c_1_reg_776 == 5'd15) & ~(c_1_reg_776 == 5'd16) & ~(c_1_reg_776 == 5'd17) & ~(c_1_reg_776 == 5'd18));
        mul_ln46_reg_825 <= grp_fu_493_p2;
        tmp_1_cast_reg_830 <= {{grp_fu_493_p2[51:36]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln6_reg_814 <= icmp_ln6_fu_547_p2;
        icmp_ln7_reg_820 <= icmp_ln7_fu_553_p2;
        tmp_2_reg_808 <= tmp_2_fu_539_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        prev_reg_798 <= beat_in_q12_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln24_fu_506_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln24_fu_506_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        beat_in_q12_address0 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_address0;
    end else begin
        beat_in_q12_address0 = zext_ln27_fu_526_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        beat_in_q12_ce0 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_beat_in_q12_ce0;
    end else begin
        beat_in_q12_ce0 = beat_in_q12_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        beat_in_q12_ce0_local = 1'b1;
    end else begin
        beat_in_q12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred305_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_0_ap_vld = 1'b1;
    end else begin
        feat_q12_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred256_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_10_ap_vld = 1'b1;
    end else begin
        feat_q12_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred251_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_11_ap_vld = 1'b1;
    end else begin
        feat_q12_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred246_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_12_ap_vld = 1'b1;
    end else begin
        feat_q12_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred241_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_13_ap_vld = 1'b1;
    end else begin
        feat_q12_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred236_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_14_ap_vld = 1'b1;
    end else begin
        feat_q12_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred231_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_15_ap_vld = 1'b1;
    end else begin
        feat_q12_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred226_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_16_ap_vld = 1'b1;
    end else begin
        feat_q12_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred221_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_17_ap_vld = 1'b1;
    end else begin
        feat_q12_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred215_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_18_ap_vld = 1'b1;
    end else begin
        feat_q12_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred345_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_19_ap_vld = 1'b1;
    end else begin
        feat_q12_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred301_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_1_ap_vld = 1'b1;
    end else begin
        feat_q12_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred305_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_20_ap_vld = 1'b1;
    end else begin
        feat_q12_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred301_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_21_ap_vld = 1'b1;
    end else begin
        feat_q12_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred296_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_22_ap_vld = 1'b1;
    end else begin
        feat_q12_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred291_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_23_ap_vld = 1'b1;
    end else begin
        feat_q12_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred286_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_24_ap_vld = 1'b1;
    end else begin
        feat_q12_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred281_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_25_ap_vld = 1'b1;
    end else begin
        feat_q12_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred276_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_26_ap_vld = 1'b1;
    end else begin
        feat_q12_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred271_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_27_ap_vld = 1'b1;
    end else begin
        feat_q12_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred266_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_28_ap_vld = 1'b1;
    end else begin
        feat_q12_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred261_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_29_ap_vld = 1'b1;
    end else begin
        feat_q12_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred296_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_2_ap_vld = 1'b1;
    end else begin
        feat_q12_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred256_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_30_ap_vld = 1'b1;
    end else begin
        feat_q12_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred251_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_31_ap_vld = 1'b1;
    end else begin
        feat_q12_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred246_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_32_ap_vld = 1'b1;
    end else begin
        feat_q12_32_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred241_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_33_ap_vld = 1'b1;
    end else begin
        feat_q12_33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred236_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_34_ap_vld = 1'b1;
    end else begin
        feat_q12_34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred231_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_35_ap_vld = 1'b1;
    end else begin
        feat_q12_35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred226_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_36_ap_vld = 1'b1;
    end else begin
        feat_q12_36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred221_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_37_ap_vld = 1'b1;
    end else begin
        feat_q12_37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred215_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_38_ap_vld = 1'b1;
    end else begin
        feat_q12_38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred345_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_39_ap_vld = 1'b1;
    end else begin
        feat_q12_39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred291_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_3_ap_vld = 1'b1;
    end else begin
        feat_q12_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred286_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_4_ap_vld = 1'b1;
    end else begin
        feat_q12_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred281_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_5_ap_vld = 1'b1;
    end else begin
        feat_q12_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred276_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_6_ap_vld = 1'b1;
    end else begin
        feat_q12_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred271_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_7_ap_vld = 1'b1;
    end else begin
        feat_q12_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred266_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_8_ap_vld = 1'b1;
    end else begin
        feat_q12_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred261_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        feat_q12_9_ap_vld = 1'b1;
    end else begin
        feat_q12_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln24_fu_506_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_512_p2 = (c_fu_178 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign feat_q12_0 = select_ln45_fu_612_p3;

assign feat_q12_1 = select_ln45_fu_612_p3;

assign feat_q12_10 = select_ln45_fu_612_p3;

assign feat_q12_11 = select_ln45_fu_612_p3;

assign feat_q12_12 = select_ln45_fu_612_p3;

assign feat_q12_13 = select_ln45_fu_612_p3;

assign feat_q12_14 = select_ln45_fu_612_p3;

assign feat_q12_15 = select_ln45_fu_612_p3;

assign feat_q12_16 = select_ln45_fu_612_p3;

assign feat_q12_17 = select_ln45_fu_612_p3;

assign feat_q12_18 = select_ln45_fu_612_p3;

assign feat_q12_19 = select_ln45_fu_612_p3;

assign feat_q12_2 = select_ln45_fu_612_p3;

assign feat_q12_20 = select_ln6_1_fu_684_p3;

assign feat_q12_21 = select_ln6_1_fu_684_p3;

assign feat_q12_22 = select_ln6_1_fu_684_p3;

assign feat_q12_23 = select_ln6_1_fu_684_p3;

assign feat_q12_24 = select_ln6_1_fu_684_p3;

assign feat_q12_25 = select_ln6_1_fu_684_p3;

assign feat_q12_26 = select_ln6_1_fu_684_p3;

assign feat_q12_27 = select_ln6_1_fu_684_p3;

assign feat_q12_28 = select_ln6_1_fu_684_p3;

assign feat_q12_29 = select_ln6_1_fu_684_p3;

assign feat_q12_3 = select_ln45_fu_612_p3;

assign feat_q12_30 = select_ln6_1_fu_684_p3;

assign feat_q12_31 = select_ln6_1_fu_684_p3;

assign feat_q12_32 = select_ln6_1_fu_684_p3;

assign feat_q12_33 = select_ln6_1_fu_684_p3;

assign feat_q12_34 = select_ln6_1_fu_684_p3;

assign feat_q12_35 = select_ln6_1_fu_684_p3;

assign feat_q12_36 = select_ln6_1_fu_684_p3;

assign feat_q12_37 = select_ln6_1_fu_684_p3;

assign feat_q12_38 = select_ln6_1_fu_684_p3;

assign feat_q12_39 = select_ln6_1_fu_684_p3;

assign feat_q12_4 = select_ln45_fu_612_p3;

assign feat_q12_5 = select_ln45_fu_612_p3;

assign feat_q12_6 = select_ln45_fu_612_p3;

assign feat_q12_7 = select_ln45_fu_612_p3;

assign feat_q12_8 = select_ln45_fu_612_p3;

assign feat_q12_9 = select_ln45_fu_612_p3;

assign grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_ap_start_reg;

assign grp_fu_493_p1 = 65'd4581298450;

assign icmp_ln24_fu_506_p2 = ((c_fu_178 == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_547_p0 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;

assign icmp_ln6_fu_547_p2 = (($signed(icmp_ln6_fu_547_p0) > $signed(32'd491519)) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_553_p0 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;

assign icmp_ln7_fu_553_p2 = (($signed(icmp_ln7_fu_553_p0) < $signed(32'd4294475762)) ? 1'b1 : 1'b0);

assign or_ln6_fu_680_p2 = (icmp_ln7_reg_820 | icmp_ln6_reg_814);

assign select_ln45_fu_612_p3 = ((tmp_fu_572_p3[0:0] == 1'b1) ? sub_ln45_1_fu_596_p2 : trunc_ln45_2_fu_602_p4);

assign select_ln46_fu_667_p3 = ((tmp_2_reg_808[0:0] == 1'b1) ? sub_ln8_fu_661_p2 : tmp_1_cast_reg_830);

assign select_ln6_1_fu_684_p3 = ((or_ln6_fu_680_p2[0:0] == 1'b1) ? select_ln6_fu_673_p3 : select_ln46_fu_667_p3);

assign select_ln6_fu_673_p3 = ((icmp_ln6_reg_814[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln8_fu_655_p3 = ((tmp_2_reg_808[0:0] == 1'b1) ? tmp_cast_fu_645_p4 : tmp_1_cast_reg_830);

assign sext_ln46_fu_534_p0 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;

assign shl_ln_fu_518_p3 = {{c_fu_178}, {4'd0}};

assign sub_ln45_1_fu_596_p2 = (16'd0 - trunc_ln45_1_fu_586_p4);

assign sub_ln45_fu_580_p2 = (20'd0 - grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out);

assign sub_ln46_fu_640_p2 = (65'd0 - mul_ln46_reg_825);

assign sub_ln8_fu_661_p2 = (16'd0 - select_ln8_fu_655_p3);

assign tmp_2_fu_539_p1 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_diff_sum_out;

assign tmp_cast_fu_645_p4 = {{sub_ln46_fu_640_p2[51:36]}};

assign tmp_fu_572_p3 = grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out[32'd19];

assign trunc_ln45_1_fu_586_p4 = {{sub_ln45_fu_580_p2[19:4]}};

assign trunc_ln45_2_fu_602_p4 = {{grp_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2_fu_483_sum_out[19:4]}};

assign zext_ln27_fu_526_p1 = shl_ln_fu_518_p3;

always @ (posedge ap_clk) begin
    shl_ln_reg_788[3:0] <= 4'b0000;
end

endmodule //ecg_fpga_top_extract_light_features_40_int
