// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_dense_24x5_linear_int (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_q12_0_val,
        in_q12_1_val,
        in_q12_2_val,
        in_q12_3_val,
        in_q12_4_val,
        in_q12_5_val,
        in_q12_6_val,
        in_q12_7_val,
        in_q12_8_val,
        in_q12_9_val,
        in_q12_10_val,
        in_q12_11_val,
        in_q12_12_val,
        in_q12_13_val,
        in_q12_14_val,
        in_q12_15_val,
        in_q12_16_val,
        in_q12_17_val,
        in_q12_18_val,
        in_q12_19_val,
        in_q12_20_val,
        in_q12_21_val,
        in_q12_22_val,
        in_q12_23_val,
        out_q12_0,
        out_q12_0_ap_vld,
        out_q12_1,
        out_q12_1_ap_vld,
        out_q12_2,
        out_q12_2_ap_vld,
        out_q12_3,
        out_q12_3_ap_vld,
        out_q12_4,
        out_q12_4_ap_vld
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [14:0] in_q12_0_val;
input  [14:0] in_q12_1_val;
input  [14:0] in_q12_2_val;
input  [14:0] in_q12_3_val;
input  [14:0] in_q12_4_val;
input  [14:0] in_q12_5_val;
input  [14:0] in_q12_6_val;
input  [14:0] in_q12_7_val;
input  [14:0] in_q12_8_val;
input  [14:0] in_q12_9_val;
input  [14:0] in_q12_10_val;
input  [14:0] in_q12_11_val;
input  [14:0] in_q12_12_val;
input  [14:0] in_q12_13_val;
input  [14:0] in_q12_14_val;
input  [14:0] in_q12_15_val;
input  [14:0] in_q12_16_val;
input  [14:0] in_q12_17_val;
input  [14:0] in_q12_18_val;
input  [14:0] in_q12_19_val;
input  [14:0] in_q12_20_val;
input  [14:0] in_q12_21_val;
input  [14:0] in_q12_22_val;
input  [14:0] in_q12_23_val;
output  [15:0] out_q12_0;
output   out_q12_0_ap_vld;
output  [15:0] out_q12_1;
output   out_q12_1_ap_vld;
output  [15:0] out_q12_2;
output   out_q12_2_ap_vld;
output  [15:0] out_q12_3;
output   out_q12_3_ap_vld;
output  [15:0] out_q12_4;
output   out_q12_4_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_q12_0_ap_vld;
reg out_q12_1_ap_vld;
reg out_q12_2_ap_vld;
reg out_q12_3_ap_vld;
reg out_q12_4_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] main5_class_output_bias_address0;
wire   [13:0] main5_class_output_bias_q0;
reg   [2:0] o_2_reg_603;
wire    ap_CS_fsm_state2;
wire   [2:0] add_ln81_fu_363_p2;
reg   [2:0] add_ln81_reg_610;
wire   [25:0] acc_fu_374_p3;
reg   [25:0] acc_reg_620;
wire    ap_CS_fsm_state3;
wire    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start;
wire    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done;
wire    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_idle;
wire    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_ready;
wire   [32:0] grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out;
wire    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out_ap_vld;
reg    grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln81_fu_369_p1;
wire   [0:0] icmp_ln81_fu_357_p2;
reg   [2:0] o_fu_116;
wire    ap_CS_fsm_state5;
wire   [15:0] select_ln6_fu_442_p3;
reg    main5_class_output_bias_ce0_local;
wire   [5:0] tmp_fu_396_p4;
wire   [20:0] trunc_ln_fu_386_p4;
wire   [0:0] icmp_ln6_fu_406_p2;
wire   [0:0] icmp_ln7_fu_412_p2;
wire   [0:0] or_ln6_fu_436_p2;
wire   [15:0] select_ln6_3_fu_428_p3;
wire   [15:0] trunc_ln8_fu_418_p4;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg = 1'b0;
#0 o_fu_116 = 3'd0;
end

ecg_fpga_top_dense_24x5_linear_int_main5_class_output_bias_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
main5_class_output_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(main5_class_output_bias_address0),
    .ce0(main5_class_output_bias_ce0_local),
    .q0(main5_class_output_bias_q0)
);

ecg_fpga_top_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2 grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start),
    .ap_done(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done),
    .ap_idle(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_idle),
    .ap_ready(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_ready),
    .sext_ln82(acc_reg_620),
    .zext_ln81_1(o_fu_116),
    .in_q12_0_val(in_q12_0_val),
    .in_q12_1_val(in_q12_1_val),
    .in_q12_2_val(in_q12_2_val),
    .in_q12_3_val(in_q12_3_val),
    .in_q12_4_val(in_q12_4_val),
    .in_q12_5_val(in_q12_5_val),
    .in_q12_6_val(in_q12_6_val),
    .in_q12_7_val(in_q12_7_val),
    .in_q12_8_val(in_q12_8_val),
    .in_q12_9_val(in_q12_9_val),
    .in_q12_10_val(in_q12_10_val),
    .in_q12_11_val(in_q12_11_val),
    .in_q12_12_val(in_q12_12_val),
    .in_q12_13_val(in_q12_13_val),
    .in_q12_14_val(in_q12_14_val),
    .in_q12_15_val(in_q12_15_val),
    .in_q12_16_val(in_q12_16_val),
    .in_q12_17_val(in_q12_17_val),
    .in_q12_18_val(in_q12_18_val),
    .in_q12_19_val(in_q12_19_val),
    .in_q12_20_val(in_q12_20_val),
    .in_q12_21_val(in_q12_21_val),
    .in_q12_22_val(in_q12_22_val),
    .in_q12_23_val(in_q12_23_val),
    .acc_2_out(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out),
    .acc_2_out_ap_vld(grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg <= 1'b1;
        end else if ((grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_ready == 1'b1)) begin
            grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_fu_116 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        o_fu_116 <= add_ln81_reg_610;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_reg_620[25 : 12] <= acc_fu_374_p3[25 : 12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln81_reg_610 <= add_ln81_fu_363_p2;
        o_2_reg_603 <= o_fu_116;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln81_fu_357_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln81_fu_357_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        main5_class_output_bias_ce0_local = 1'b1;
    end else begin
        main5_class_output_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (o_2_reg_603 == 3'd0))) begin
        out_q12_0_ap_vld = 1'b1;
    end else begin
        out_q12_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (o_2_reg_603 == 3'd1))) begin
        out_q12_1_ap_vld = 1'b1;
    end else begin
        out_q12_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (o_2_reg_603 == 3'd2))) begin
        out_q12_2_ap_vld = 1'b1;
    end else begin
        out_q12_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (o_2_reg_603 == 3'd3))) begin
        out_q12_3_ap_vld = 1'b1;
    end else begin
        out_q12_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(o_2_reg_603 == 3'd0) & ~(o_2_reg_603 == 3'd1) & ~(o_2_reg_603 == 3'd2) & ~(o_2_reg_603 == 3'd3) & (1'b1 == ap_CS_fsm_state5))) begin
        out_q12_4_ap_vld = 1'b1;
    end else begin
        out_q12_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln81_fu_357_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_374_p3 = {{main5_class_output_bias_q0}, {12'd0}};

assign add_ln81_fu_363_p2 = (o_fu_116 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start = grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_ap_start_reg;

assign icmp_ln6_fu_406_p2 = (($signed(tmp_fu_396_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_412_p2 = (($signed(trunc_ln_fu_386_p4) < $signed(21'd2064384)) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_357_p2 = ((o_fu_116 == 3'd5) ? 1'b1 : 1'b0);

assign main5_class_output_bias_address0 = zext_ln81_fu_369_p1;

assign or_ln6_fu_436_p2 = (icmp_ln7_fu_412_p2 | icmp_ln6_fu_406_p2);

assign out_q12_0 = select_ln6_fu_442_p3;

assign out_q12_1 = select_ln6_fu_442_p3;

assign out_q12_2 = select_ln6_fu_442_p3;

assign out_q12_3 = select_ln6_fu_442_p3;

assign out_q12_4 = select_ln6_fu_442_p3;

assign select_ln6_3_fu_428_p3 = ((icmp_ln6_fu_406_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln6_fu_442_p3 = ((or_ln6_fu_436_p2[0:0] == 1'b1) ? select_ln6_3_fu_428_p3 : trunc_ln8_fu_418_p4);

assign tmp_fu_396_p4 = {{grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out[32:27]}};

assign trunc_ln8_fu_418_p4 = {{grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out[27:12]}};

assign trunc_ln_fu_386_p4 = {{grp_dense_24x5_linear_int_Pipeline_VITIS_LOOP_84_2_fu_316_acc_2_out[32:12]}};

assign zext_ln81_fu_369_p1 = o_fu_116;

always @ (posedge ap_clk) begin
    acc_reg_620[11:0] <= 12'b000000000000;
end

endmodule //ecg_fpga_top_dense_24x5_linear_int
