// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        prev,
        shl_ln,
        beat_in_q12_address0,
        beat_in_q12_ce0,
        beat_in_q12_q0,
        sum_out,
        sum_out_ap_vld,
        diff_sum_out,
        diff_sum_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] prev;
input  [8:0] shl_ln;
output  [8:0] beat_in_q12_address0;
output   beat_in_q12_ce0;
input  [15:0] beat_in_q12_q0;
output  [19:0] sum_out;
output   sum_out_ap_vld;
output  [31:0] diff_sum_out;
output   diff_sum_out_ap_vld;

reg ap_idle;
reg sum_out_ap_vld;
reg diff_sum_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln29_fu_136_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln29_reg_318;
reg   [0:0] icmp_ln29_reg_318_pp0_iter1_reg;
wire   [0:0] icmp_ln35_fu_163_p2;
reg   [0:0] icmp_ln35_reg_327;
reg   [0:0] icmp_ln35_reg_327_pp0_iter1_reg;
reg   [0:0] icmp_ln35_reg_327_pp0_iter2_reg;
reg  signed [15:0] x_reg_332;
wire   [15:0] trunc_ln36_fu_208_p1;
reg   [15:0] trunc_ln36_reg_338;
reg   [0:0] tmp_reg_343;
wire   [15:0] sub_ln37_fu_220_p2;
reg   [15:0] sub_ln37_reg_348;
wire   [63:0] zext_ln32_fu_158_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] prev_1_fu_58;
wire    ap_loop_init;
reg   [31:0] diff_sum_fu_62;
wire   [31:0] diff_sum_1_fu_268_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [19:0] sum_fu_66;
wire   [19:0] sum_1_fu_181_p2;
reg   [4:0] j_fu_70;
wire   [4:0] add_ln29_fu_142_p2;
reg   [4:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage0_01001;
reg    beat_in_q12_ce0_local;
wire   [8:0] zext_ln29_fu_148_p1;
wire   [8:0] add_ln31_fu_152_p2;
wire  signed [15:0] sext_ln33_1_fu_177_p0;
wire  signed [19:0] sext_ln33_1_fu_177_p1;
wire  signed [15:0] sext_ln36_fu_198_p0;
wire  signed [16:0] sext_ln33_fu_195_p1;
wire  signed [16:0] sext_ln36_fu_198_p1;
wire   [16:0] d_fu_202_p2;
wire   [15:0] d_1_fu_233_p3;
wire   [0:0] tmp_1_fu_242_p3;
wire   [14:0] trunc_ln36_1_fu_238_p1;
wire   [14:0] d_2_fu_250_p3;
wire   [31:0] zext_ln36_fu_258_p1;
wire   [31:0] diff_sum_2_fu_262_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 prev_1_fu_58 = 16'd0;
#0 diff_sum_fu_62 = 32'd0;
#0 sum_fu_66 = 20'd0;
#0 j_fu_70 = 5'd0;
#0 ap_done_reg = 1'b0;
end

ecg_fpga_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            diff_sum_fu_62 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            diff_sum_fu_62 <= diff_sum_1_fu_268_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln29_fu_136_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_70 <= add_ln29_fu_142_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_70 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            prev_1_fu_58 <= prev;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            prev_1_fu_58 <= x_reg_332;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sum_fu_66 <= 20'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            sum_fu_66 <= sum_1_fu_181_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln29_reg_318 <= icmp_ln29_fu_136_p2;
        icmp_ln29_reg_318_pp0_iter1_reg <= icmp_ln29_reg_318;
        icmp_ln35_reg_327 <= icmp_ln35_fu_163_p2;
        icmp_ln35_reg_327_pp0_iter1_reg <= icmp_ln35_reg_327;
        x_reg_332 <= beat_in_q12_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln35_reg_327_pp0_iter2_reg <= icmp_ln35_reg_327_pp0_iter1_reg;
        sub_ln37_reg_348 <= sub_ln37_fu_220_p2;
        tmp_reg_343 <= d_fu_202_p2[32'd16];
        trunc_ln36_reg_338 <= trunc_ln36_fu_208_p1;
    end
end

always @ (*) begin
    if (((icmp_ln29_fu_136_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        beat_in_q12_ce0_local = 1'b1;
    end else begin
        beat_in_q12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_318_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        diff_sum_out_ap_vld = 1'b1;
    end else begin
        diff_sum_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_318_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        sum_out_ap_vld = 1'b1;
    end else begin
        sum_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_fu_142_p2 = (ap_sig_allocacmp_j_1 + 5'd1);

assign add_ln31_fu_152_p2 = (zext_ln29_fu_148_p1 + shl_ln);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign beat_in_q12_address0 = zext_ln32_fu_158_p1;

assign beat_in_q12_ce0 = beat_in_q12_ce0_local;

assign d_1_fu_233_p3 = ((tmp_reg_343[0:0] == 1'b1) ? sub_ln37_reg_348 : trunc_ln36_reg_338);

assign d_2_fu_250_p3 = ((tmp_1_fu_242_p3[0:0] == 1'b1) ? 15'd32767 : trunc_ln36_1_fu_238_p1);

assign d_fu_202_p2 = ($signed(sext_ln33_fu_195_p1) - $signed(sext_ln36_fu_198_p1));

assign diff_sum_1_fu_268_p3 = ((icmp_ln35_reg_327_pp0_iter2_reg[0:0] == 1'b1) ? diff_sum_2_fu_262_p2 : diff_sum_fu_62);

assign diff_sum_2_fu_262_p2 = (zext_ln36_fu_258_p1 + diff_sum_fu_62);

assign diff_sum_out = diff_sum_fu_62;

assign icmp_ln29_fu_136_p2 = ((ap_sig_allocacmp_j_1 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_163_p2 = ((ap_sig_allocacmp_j_1 != 5'd0) ? 1'b1 : 1'b0);

assign sext_ln33_1_fu_177_p0 = beat_in_q12_q0;

assign sext_ln33_1_fu_177_p1 = sext_ln33_1_fu_177_p0;

assign sext_ln33_fu_195_p1 = x_reg_332;

assign sext_ln36_fu_198_p0 = prev_1_fu_58;

assign sext_ln36_fu_198_p1 = sext_ln36_fu_198_p0;

assign sub_ln37_fu_220_p2 = (16'd0 - trunc_ln36_fu_208_p1);

assign sum_1_fu_181_p2 = ($signed(sext_ln33_1_fu_177_p1) + $signed(sum_fu_66));

assign sum_out = sum_fu_66;

assign tmp_1_fu_242_p3 = d_1_fu_233_p3[32'd15];

assign trunc_ln36_1_fu_238_p1 = d_1_fu_233_p3[14:0];

assign trunc_ln36_fu_208_p1 = d_fu_202_p2[15:0];

assign zext_ln29_fu_148_p1 = ap_sig_allocacmp_j_1;

assign zext_ln32_fu_158_p1 = add_ln31_fu_152_p2;

assign zext_ln36_fu_258_p1 = d_2_fu_250_p3;

endmodule //ecg_fpga_top_extract_light_features_40_int_Pipeline_VITIS_LOOP_29_2
